// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_ReLU_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer28_out_dout,
        layer28_out_empty_n,
        layer28_out_read,
        layer28_out_num_data_valid,
        layer28_out_fifo_cap,
        layer15_out_din,
        layer15_out_full_n,
        layer15_out_write,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer28_out_dout;
input   layer28_out_empty_n;
output   layer28_out_read;
input  [7:0] layer28_out_num_data_valid;
input  [7:0] layer28_out_fifo_cap;
output  [255:0] layer15_out_din;
input   layer15_out_full_n;
output   layer15_out_write;
input  [31:0] layer15_out_num_data_valid;
input  [31:0] layer15_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer28_out_read;
reg layer15_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_475_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer28_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    layer15_out_blk_n;
wire   [15:0] trunc_ln44_fu_161_p1;
reg   [15:0] trunc_ln44_reg_770;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [14:0] trunc_ln44_83_fu_165_p1;
reg   [14:0] trunc_ln44_83_reg_775;
reg   [15:0] trunc_ln44_39_reg_780;
reg   [14:0] trunc_ln44_s_reg_785;
reg   [15:0] trunc_ln44_40_reg_790;
reg   [14:0] trunc_ln44_68_reg_795;
reg   [15:0] trunc_ln44_41_reg_800;
reg   [14:0] trunc_ln44_69_reg_805;
reg   [15:0] trunc_ln44_42_reg_810;
reg   [14:0] trunc_ln44_70_reg_815;
reg   [15:0] trunc_ln44_43_reg_820;
reg   [14:0] trunc_ln44_71_reg_825;
reg   [15:0] trunc_ln44_44_reg_830;
reg   [14:0] trunc_ln44_72_reg_835;
reg   [15:0] trunc_ln44_45_reg_840;
reg   [14:0] trunc_ln44_73_reg_845;
reg   [15:0] trunc_ln44_46_reg_850;
reg   [14:0] trunc_ln44_74_reg_855;
reg   [15:0] trunc_ln44_47_reg_860;
reg   [14:0] trunc_ln44_75_reg_865;
reg   [15:0] trunc_ln44_48_reg_870;
reg   [14:0] trunc_ln44_76_reg_875;
reg   [15:0] trunc_ln44_49_reg_880;
reg   [14:0] trunc_ln44_77_reg_885;
reg   [15:0] trunc_ln44_50_reg_890;
reg   [14:0] trunc_ln44_78_reg_895;
reg   [15:0] trunc_ln44_51_reg_900;
reg   [14:0] trunc_ln44_79_reg_905;
reg   [15:0] trunc_ln44_52_reg_910;
reg   [14:0] trunc_ln44_80_reg_915;
reg   [15:0] trunc_ln44_53_reg_920;
reg   [14:0] trunc_ln3_reg_925;
reg    ap_block_pp0_stage0_11001;
wire   [14:0] select_ln51_fu_491_p3;
reg   [14:0] select_ln51_reg_934;
wire   [14:0] select_ln51_39_fu_503_p3;
reg   [14:0] select_ln51_39_reg_939;
wire   [14:0] select_ln51_40_fu_515_p3;
reg   [14:0] select_ln51_40_reg_944;
wire   [14:0] select_ln51_41_fu_527_p3;
reg   [14:0] select_ln51_41_reg_949;
wire   [14:0] select_ln51_42_fu_539_p3;
reg   [14:0] select_ln51_42_reg_954;
wire   [14:0] select_ln51_43_fu_551_p3;
reg   [14:0] select_ln51_43_reg_959;
wire   [14:0] select_ln51_44_fu_563_p3;
reg   [14:0] select_ln51_44_reg_964;
wire   [14:0] select_ln51_45_fu_575_p3;
reg   [14:0] select_ln51_45_reg_969;
wire   [14:0] select_ln51_46_fu_587_p3;
reg   [14:0] select_ln51_46_reg_974;
wire   [14:0] select_ln51_47_fu_599_p3;
reg   [14:0] select_ln51_47_reg_979;
wire   [14:0] select_ln51_48_fu_611_p3;
reg   [14:0] select_ln51_48_reg_984;
wire   [14:0] select_ln51_49_fu_623_p3;
reg   [14:0] select_ln51_49_reg_989;
wire   [14:0] select_ln51_50_fu_635_p3;
reg   [14:0] select_ln51_50_reg_994;
wire   [14:0] select_ln51_51_fu_647_p3;
reg   [14:0] select_ln51_51_reg_999;
wire   [14:0] select_ln51_52_fu_659_p3;
reg   [14:0] select_ln51_52_reg_1004;
wire   [14:0] select_ln51_53_fu_671_p3;
reg   [14:0] select_ln51_53_reg_1009;
reg   [6:0] i_fu_136;
wire   [6:0] i_7_fu_469_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] icmp_ln51_fu_486_p2;
wire   [0:0] icmp_ln51_39_fu_498_p2;
wire   [0:0] icmp_ln51_40_fu_510_p2;
wire   [0:0] icmp_ln51_41_fu_522_p2;
wire   [0:0] icmp_ln51_42_fu_534_p2;
wire   [0:0] icmp_ln51_43_fu_546_p2;
wire   [0:0] icmp_ln51_44_fu_558_p2;
wire   [0:0] icmp_ln51_45_fu_570_p2;
wire   [0:0] icmp_ln51_46_fu_582_p2;
wire   [0:0] icmp_ln51_47_fu_594_p2;
wire   [0:0] icmp_ln51_48_fu_606_p2;
wire   [0:0] icmp_ln51_49_fu_618_p2;
wire   [0:0] icmp_ln51_50_fu_630_p2;
wire   [0:0] icmp_ln51_51_fu_642_p2;
wire   [0:0] icmp_ln51_52_fu_654_p2;
wire   [0:0] icmp_ln51_53_fu_666_p2;
wire   [15:0] zext_ln51_50_fu_720_p1;
wire   [15:0] zext_ln51_49_fu_717_p1;
wire   [15:0] zext_ln51_48_fu_714_p1;
wire   [15:0] zext_ln51_47_fu_711_p1;
wire   [15:0] zext_ln51_46_fu_708_p1;
wire   [15:0] zext_ln51_45_fu_705_p1;
wire   [15:0] zext_ln51_44_fu_702_p1;
wire   [15:0] zext_ln51_43_fu_699_p1;
wire   [15:0] zext_ln51_42_fu_696_p1;
wire   [15:0] zext_ln51_41_fu_693_p1;
wire   [15:0] zext_ln51_40_fu_690_p1;
wire   [15:0] zext_ln51_39_fu_687_p1;
wire   [15:0] zext_ln51_38_fu_684_p1;
wire   [15:0] zext_ln51_37_fu_681_p1;
wire   [15:0] zext_ln51_fu_678_p1;
wire   [254:0] or_ln57_s_fu_723_p17;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_136 = 7'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            i_fu_136 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_136 <= i_7_fu_469_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        select_ln51_39_reg_939 <= select_ln51_39_fu_503_p3;
        select_ln51_40_reg_944 <= select_ln51_40_fu_515_p3;
        select_ln51_41_reg_949 <= select_ln51_41_fu_527_p3;
        select_ln51_42_reg_954 <= select_ln51_42_fu_539_p3;
        select_ln51_43_reg_959 <= select_ln51_43_fu_551_p3;
        select_ln51_44_reg_964 <= select_ln51_44_fu_563_p3;
        select_ln51_45_reg_969 <= select_ln51_45_fu_575_p3;
        select_ln51_46_reg_974 <= select_ln51_46_fu_587_p3;
        select_ln51_47_reg_979 <= select_ln51_47_fu_599_p3;
        select_ln51_48_reg_984 <= select_ln51_48_fu_611_p3;
        select_ln51_49_reg_989 <= select_ln51_49_fu_623_p3;
        select_ln51_50_reg_994 <= select_ln51_50_fu_635_p3;
        select_ln51_51_reg_999 <= select_ln51_51_fu_647_p3;
        select_ln51_52_reg_1004 <= select_ln51_52_fu_659_p3;
        select_ln51_53_reg_1009 <= select_ln51_53_fu_671_p3;
        select_ln51_reg_934 <= select_ln51_fu_491_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln3_reg_925 <= {{layer28_out_dout[254:240]}};
        trunc_ln44_39_reg_780 <= {{layer28_out_dout[31:16]}};
        trunc_ln44_40_reg_790 <= {{layer28_out_dout[47:32]}};
        trunc_ln44_41_reg_800 <= {{layer28_out_dout[63:48]}};
        trunc_ln44_42_reg_810 <= {{layer28_out_dout[79:64]}};
        trunc_ln44_43_reg_820 <= {{layer28_out_dout[95:80]}};
        trunc_ln44_44_reg_830 <= {{layer28_out_dout[111:96]}};
        trunc_ln44_45_reg_840 <= {{layer28_out_dout[127:112]}};
        trunc_ln44_46_reg_850 <= {{layer28_out_dout[143:128]}};
        trunc_ln44_47_reg_860 <= {{layer28_out_dout[159:144]}};
        trunc_ln44_48_reg_870 <= {{layer28_out_dout[175:160]}};
        trunc_ln44_49_reg_880 <= {{layer28_out_dout[191:176]}};
        trunc_ln44_50_reg_890 <= {{layer28_out_dout[207:192]}};
        trunc_ln44_51_reg_900 <= {{layer28_out_dout[223:208]}};
        trunc_ln44_52_reg_910 <= {{layer28_out_dout[239:224]}};
        trunc_ln44_53_reg_920 <= {{layer28_out_dout[255:240]}};
        trunc_ln44_68_reg_795 <= {{layer28_out_dout[46:32]}};
        trunc_ln44_69_reg_805 <= {{layer28_out_dout[62:48]}};
        trunc_ln44_70_reg_815 <= {{layer28_out_dout[78:64]}};
        trunc_ln44_71_reg_825 <= {{layer28_out_dout[94:80]}};
        trunc_ln44_72_reg_835 <= {{layer28_out_dout[110:96]}};
        trunc_ln44_73_reg_845 <= {{layer28_out_dout[126:112]}};
        trunc_ln44_74_reg_855 <= {{layer28_out_dout[142:128]}};
        trunc_ln44_75_reg_865 <= {{layer28_out_dout[158:144]}};
        trunc_ln44_76_reg_875 <= {{layer28_out_dout[174:160]}};
        trunc_ln44_77_reg_885 <= {{layer28_out_dout[190:176]}};
        trunc_ln44_78_reg_895 <= {{layer28_out_dout[206:192]}};
        trunc_ln44_79_reg_905 <= {{layer28_out_dout[222:208]}};
        trunc_ln44_80_reg_915 <= {{layer28_out_dout[238:224]}};
        trunc_ln44_83_reg_775 <= trunc_ln44_83_fu_165_p1;
        trunc_ln44_reg_770 <= trunc_ln44_fu_161_p1;
        trunc_ln44_s_reg_785 <= {{layer28_out_dout[30:16]}};
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_475_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer15_out_blk_n = layer15_out_full_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer15_out_write = 1'b1;
    end else begin
        layer15_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer28_out_blk_n = layer28_out_empty_n;
    end else begin
        layer28_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer28_out_read = 1'b1;
    end else begin
        layer28_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((layer15_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer28_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer15_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer28_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((layer15_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer28_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer15_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer28_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = internal_ap_ready;

assign i_7_fu_469_p2 = (i_fu_136 + 7'd1);

assign icmp_ln41_fu_475_p2 = ((i_fu_136 == 7'd120) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_498_p2 = (($signed(trunc_ln44_39_reg_780) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_510_p2 = (($signed(trunc_ln44_40_reg_790) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_522_p2 = (($signed(trunc_ln44_41_reg_800) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_534_p2 = (($signed(trunc_ln44_42_reg_810) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_546_p2 = (($signed(trunc_ln44_43_reg_820) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_558_p2 = (($signed(trunc_ln44_44_reg_830) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_570_p2 = (($signed(trunc_ln44_45_reg_840) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_582_p2 = (($signed(trunc_ln44_46_reg_850) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_47_fu_594_p2 = (($signed(trunc_ln44_47_reg_860) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_48_fu_606_p2 = (($signed(trunc_ln44_48_reg_870) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_49_fu_618_p2 = (($signed(trunc_ln44_49_reg_880) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_50_fu_630_p2 = (($signed(trunc_ln44_50_reg_890) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_51_fu_642_p2 = (($signed(trunc_ln44_51_reg_900) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_52_fu_654_p2 = (($signed(trunc_ln44_52_reg_910) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_53_fu_666_p2 = (($signed(trunc_ln44_53_reg_920) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_486_p2 = (($signed(trunc_ln44_reg_770) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign layer15_out_din = or_ln57_s_fu_723_p17;

assign or_ln57_s_fu_723_p17 = {{{{{{{{{{{{{{{{select_ln51_53_reg_1009}, {zext_ln51_50_fu_720_p1}}, {zext_ln51_49_fu_717_p1}}, {zext_ln51_48_fu_714_p1}}, {zext_ln51_47_fu_711_p1}}, {zext_ln51_46_fu_708_p1}}, {zext_ln51_45_fu_705_p1}}, {zext_ln51_44_fu_702_p1}}, {zext_ln51_43_fu_699_p1}}, {zext_ln51_42_fu_696_p1}}, {zext_ln51_41_fu_693_p1}}, {zext_ln51_40_fu_690_p1}}, {zext_ln51_39_fu_687_p1}}, {zext_ln51_38_fu_684_p1}}, {zext_ln51_37_fu_681_p1}}, {zext_ln51_fu_678_p1}};

assign select_ln51_39_fu_503_p3 = ((icmp_ln51_39_fu_498_p2[0:0] == 1'b1) ? trunc_ln44_s_reg_785 : 15'd0);

assign select_ln51_40_fu_515_p3 = ((icmp_ln51_40_fu_510_p2[0:0] == 1'b1) ? trunc_ln44_68_reg_795 : 15'd0);

assign select_ln51_41_fu_527_p3 = ((icmp_ln51_41_fu_522_p2[0:0] == 1'b1) ? trunc_ln44_69_reg_805 : 15'd0);

assign select_ln51_42_fu_539_p3 = ((icmp_ln51_42_fu_534_p2[0:0] == 1'b1) ? trunc_ln44_70_reg_815 : 15'd0);

assign select_ln51_43_fu_551_p3 = ((icmp_ln51_43_fu_546_p2[0:0] == 1'b1) ? trunc_ln44_71_reg_825 : 15'd0);

assign select_ln51_44_fu_563_p3 = ((icmp_ln51_44_fu_558_p2[0:0] == 1'b1) ? trunc_ln44_72_reg_835 : 15'd0);

assign select_ln51_45_fu_575_p3 = ((icmp_ln51_45_fu_570_p2[0:0] == 1'b1) ? trunc_ln44_73_reg_845 : 15'd0);

assign select_ln51_46_fu_587_p3 = ((icmp_ln51_46_fu_582_p2[0:0] == 1'b1) ? trunc_ln44_74_reg_855 : 15'd0);

assign select_ln51_47_fu_599_p3 = ((icmp_ln51_47_fu_594_p2[0:0] == 1'b1) ? trunc_ln44_75_reg_865 : 15'd0);

assign select_ln51_48_fu_611_p3 = ((icmp_ln51_48_fu_606_p2[0:0] == 1'b1) ? trunc_ln44_76_reg_875 : 15'd0);

assign select_ln51_49_fu_623_p3 = ((icmp_ln51_49_fu_618_p2[0:0] == 1'b1) ? trunc_ln44_77_reg_885 : 15'd0);

assign select_ln51_50_fu_635_p3 = ((icmp_ln51_50_fu_630_p2[0:0] == 1'b1) ? trunc_ln44_78_reg_895 : 15'd0);

assign select_ln51_51_fu_647_p3 = ((icmp_ln51_51_fu_642_p2[0:0] == 1'b1) ? trunc_ln44_79_reg_905 : 15'd0);

assign select_ln51_52_fu_659_p3 = ((icmp_ln51_52_fu_654_p2[0:0] == 1'b1) ? trunc_ln44_80_reg_915 : 15'd0);

assign select_ln51_53_fu_671_p3 = ((icmp_ln51_53_fu_666_p2[0:0] == 1'b1) ? trunc_ln3_reg_925 : 15'd0);

assign select_ln51_fu_491_p3 = ((icmp_ln51_fu_486_p2[0:0] == 1'b1) ? trunc_ln44_83_reg_775 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_83_fu_165_p1 = layer28_out_dout[14:0];

assign trunc_ln44_fu_161_p1 = layer28_out_dout[15:0];

assign zext_ln51_37_fu_681_p1 = select_ln51_39_reg_939;

assign zext_ln51_38_fu_684_p1 = select_ln51_40_reg_944;

assign zext_ln51_39_fu_687_p1 = select_ln51_41_reg_949;

assign zext_ln51_40_fu_690_p1 = select_ln51_42_reg_954;

assign zext_ln51_41_fu_693_p1 = select_ln51_43_reg_959;

assign zext_ln51_42_fu_696_p1 = select_ln51_44_reg_964;

assign zext_ln51_43_fu_699_p1 = select_ln51_45_reg_969;

assign zext_ln51_44_fu_702_p1 = select_ln51_46_reg_974;

assign zext_ln51_45_fu_705_p1 = select_ln51_47_reg_979;

assign zext_ln51_46_fu_708_p1 = select_ln51_48_reg_984;

assign zext_ln51_47_fu_711_p1 = select_ln51_49_reg_989;

assign zext_ln51_48_fu_714_p1 = select_ln51_50_reg_994;

assign zext_ln51_49_fu_717_p1 = select_ln51_51_reg_999;

assign zext_ln51_50_fu_720_p1 = select_ln51_52_reg_1004;

assign zext_ln51_fu_678_p1 = select_ln51_reg_934;

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_ReLU_config15_s
