// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer27_out_dout,
        layer27_out_empty_n,
        layer27_out_read,
        layer27_out_num_data_valid,
        layer27_out_fifo_cap,
        layer12_out_din,
        layer12_out_full_n,
        layer12_out_write,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] layer27_out_dout;
input   layer27_out_empty_n;
output   layer27_out_read;
input  [10:0] layer27_out_num_data_valid;
input  [10:0] layer27_out_fifo_cap;
output  [63:0] layer12_out_din;
input   layer12_out_full_n;
output   layer12_out_write;
input  [31:0] layer12_out_num_data_valid;
input  [31:0] layer12_out_fifo_cap;

reg ap_idle;
reg start_write;
reg layer27_out_read;
reg layer12_out_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_done_reg;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln41_fu_211_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer27_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    layer12_out_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
wire   [15:0] trunc_ln44_fu_86_p1;
reg   [15:0] trunc_ln44_reg_253;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [14:0] trunc_ln44_16_fu_90_p1;
reg   [14:0] trunc_ln44_16_reg_258;
reg   [15:0] trunc_ln44_8_reg_263;
reg   [14:0] trunc_ln44_s_reg_268;
reg   [15:0] trunc_ln44_9_reg_273;
reg   [14:0] trunc_ln44_13_reg_278;
reg   [15:0] trunc_ln44_10_reg_283;
reg   [14:0] trunc_ln2_reg_288;
wire   [14:0] select_ln51_fu_162_p3;
reg   [14:0] select_ln51_reg_293;
reg    ap_block_pp0_stage1_11001;
wire   [14:0] select_ln51_8_fu_174_p3;
reg   [14:0] select_ln51_8_reg_298;
wire   [14:0] select_ln51_9_fu_186_p3;
reg   [14:0] select_ln51_9_reg_303;
wire   [14:0] select_ln51_10_fu_198_p3;
reg   [14:0] select_ln51_10_reg_308;
wire   [9:0] i_7_fu_205_p2;
reg   [9:0] i_7_reg_313;
reg   [9:0] i_fu_64;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
reg    ap_block_pp0_stage0_subdone_grp0;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg_iter0;
wire    ap_block_pp0_stage1;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg_iter0;
reg    ap_block_pp0_stage0_01001_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
wire   [0:0] icmp_ln51_fu_157_p2;
wire   [0:0] icmp_ln51_8_fu_169_p2;
wire   [0:0] icmp_ln51_9_fu_181_p2;
wire   [0:0] icmp_ln51_10_fu_193_p2;
wire   [15:0] zext_ln51_8_fu_223_p1;
wire   [15:0] zext_ln51_7_fu_220_p1;
wire   [15:0] zext_ln51_fu_217_p1;
wire   [62:0] or_ln57_s_fu_226_p5;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_idle_pp0_0to0;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_352;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 i_fu_64 = 10'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg_iter0 = 1'b0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg_iter0 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0_0to0 == 1'b1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_352)) begin
            i_fu_64 <= 10'd0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_64 <= i_7_reg_313;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_7_reg_313 <= i_7_fu_205_p2;
        select_ln51_10_reg_308 <= select_ln51_10_fu_198_p3;
        select_ln51_8_reg_298 <= select_ln51_8_fu_174_p3;
        select_ln51_9_reg_303 <= select_ln51_9_fu_186_p3;
        select_ln51_reg_293 <= select_ln51_fu_162_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln2_reg_288 <= {{layer27_out_dout[62:48]}};
        trunc_ln44_10_reg_283 <= {{layer27_out_dout[63:48]}};
        trunc_ln44_13_reg_278 <= {{layer27_out_dout[46:32]}};
        trunc_ln44_16_reg_258 <= trunc_ln44_16_fu_90_p1;
        trunc_ln44_8_reg_263 <= {{layer27_out_dout[31:16]}};
        trunc_ln44_9_reg_273 <= {{layer27_out_dout[47:32]}};
        trunc_ln44_reg_253 <= trunc_ln44_fu_86_p1;
        trunc_ln44_s_reg_268 <= {{layer27_out_dout[30:16]}};
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_211_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer12_out_blk_n = layer12_out_full_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer12_out_write = 1'b1;
    end else begin
        layer12_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer27_out_blk_n = layer27_out_empty_n;
    end else begin
        layer27_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer27_out_read = 1'b1;
    end else begin
        layer27_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0_0to0 == 1'b1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg_iter0) & (ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((layer12_out_full_n == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg_iter0) & (ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((layer12_out_full_n == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)))) | ((layer12_out_full_n == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg_iter0) & (ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((layer12_out_full_n == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((layer27_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_condition_352 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = internal_ap_ready;

assign i_7_fu_205_p2 = (i_fu_64 + 10'd1);

assign icmp_ln41_fu_211_p2 = ((i_fu_64 == 10'd675) ? 1'b1 : 1'b0);

assign icmp_ln51_10_fu_193_p2 = (($signed(trunc_ln44_10_reg_283) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_169_p2 = (($signed(trunc_ln44_8_reg_263) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_181_p2 = (($signed(trunc_ln44_9_reg_273) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_157_p2 = (($signed(trunc_ln44_reg_253) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign layer12_out_din = or_ln57_s_fu_226_p5;

assign or_ln57_s_fu_226_p5 = {{{{select_ln51_10_reg_308}, {zext_ln51_8_fu_223_p1}}, {zext_ln51_7_fu_220_p1}}, {zext_ln51_fu_217_p1}};

assign select_ln51_10_fu_198_p3 = ((icmp_ln51_10_fu_193_p2[0:0] == 1'b1) ? trunc_ln2_reg_288 : 15'd0);

assign select_ln51_8_fu_174_p3 = ((icmp_ln51_8_fu_169_p2[0:0] == 1'b1) ? trunc_ln44_s_reg_268 : 15'd0);

assign select_ln51_9_fu_186_p3 = ((icmp_ln51_9_fu_181_p2[0:0] == 1'b1) ? trunc_ln44_13_reg_278 : 15'd0);

assign select_ln51_fu_162_p3 = ((icmp_ln51_fu_157_p2[0:0] == 1'b1) ? trunc_ln44_16_reg_258 : 15'd0);

assign start_out = real_start;

assign trunc_ln44_16_fu_90_p1 = layer27_out_dout[14:0];

assign trunc_ln44_fu_86_p1 = layer27_out_dout[15:0];

assign zext_ln51_7_fu_220_p1 = select_ln51_8_reg_298;

assign zext_ln51_8_fu_223_p1 = select_ln51_9_reg_303;

assign zext_ln51_fu_217_p1 = select_ln51_reg_293;

endmodule //myproject_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_s
