-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer26_out_dout : IN STD_LOGIC_VECTOR (751 downto 0);
    layer26_out_empty_n : IN STD_LOGIC;
    layer26_out_read : OUT STD_LOGIC;
    layer26_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer26_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer24_out_TDATA : OUT STD_LOGIC_VECTOR (751 downto 0);
    layer24_out_TVALID : OUT STD_LOGIC;
    layer24_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv32_20F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000001111";
    constant ap_const_lv32_210 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000010000";
    constant ap_const_lv32_21F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000011111";
    constant ap_const_lv32_220 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000100000";
    constant ap_const_lv32_22F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000101111";
    constant ap_const_lv32_230 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000110000";
    constant ap_const_lv32_23F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111111";
    constant ap_const_lv32_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000000";
    constant ap_const_lv32_24F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001001111";
    constant ap_const_lv32_250 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001010000";
    constant ap_const_lv32_25F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001011111";
    constant ap_const_lv32_260 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001100000";
    constant ap_const_lv32_26F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001101111";
    constant ap_const_lv32_270 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001110000";
    constant ap_const_lv32_27F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001111111";
    constant ap_const_lv32_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000000";
    constant ap_const_lv32_28F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010001111";
    constant ap_const_lv32_290 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010010000";
    constant ap_const_lv32_29F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010011111";
    constant ap_const_lv32_2A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010100000";
    constant ap_const_lv32_2AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010101111";
    constant ap_const_lv32_2B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010110000";
    constant ap_const_lv32_2BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010111111";
    constant ap_const_lv32_2C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011000000";
    constant ap_const_lv32_2CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011001111";
    constant ap_const_lv32_2D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011010000";
    constant ap_const_lv32_2DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011011111";
    constant ap_const_lv32_2E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011100000";
    constant ap_const_lv32_2EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011101111";
    constant ap_const_lv16_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_const_lv16_FF4B : STD_LOGIC_VECTOR (15 downto 0) := "1111111101001011";
    constant ap_const_lv16_3E : STD_LOGIC_VECTOR (15 downto 0) := "0000000000111110";
    constant ap_const_lv16_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010100";
    constant ap_const_lv16_FFDC : STD_LOGIC_VECTOR (15 downto 0) := "1111111111011100";
    constant ap_const_lv16_4A : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001010";
    constant ap_const_lv16_6B : STD_LOGIC_VECTOR (15 downto 0) := "0000000001101011";
    constant ap_const_lv16_FFCC : STD_LOGIC_VECTOR (15 downto 0) := "1111111111001100";
    constant ap_const_lv16_FFF8 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111000";
    constant ap_const_lv16_70 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001110000";
    constant ap_const_lv16_26 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100110";
    constant ap_const_lv16_FF8C : STD_LOGIC_VECTOR (15 downto 0) := "1111111110001100";
    constant ap_const_lv16_C3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011000011";
    constant ap_const_lv16_FF34 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100110100";
    constant ap_const_lv16_112 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100010010";
    constant ap_const_lv16_73 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001110011";
    constant ap_const_lv16_FF81 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000001";
    constant ap_const_lv16_60 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100000";
    constant ap_const_lv16_5C : STD_LOGIC_VECTOR (15 downto 0) := "0000000001011100";
    constant ap_const_lv16_FFDE : STD_LOGIC_VECTOR (15 downto 0) := "1111111111011110";
    constant ap_const_lv16_58 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001011000";
    constant ap_const_lv16_8F : STD_LOGIC_VECTOR (15 downto 0) := "0000000010001111";
    constant ap_const_lv16_FF55 : STD_LOGIC_VECTOR (15 downto 0) := "1111111101010101";
    constant ap_const_lv16_E8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011101000";
    constant ap_const_lv16_3A : STD_LOGIC_VECTOR (15 downto 0) := "0000000000111010";
    constant ap_const_lv16_FEE2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111011100010";
    constant ap_const_lv16_FFD1 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111010001";
    constant ap_const_lv16_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010111";
    constant ap_const_lv16_61 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100001";
    constant ap_const_lv16_FE38 : STD_LOGIC_VECTOR (15 downto 0) := "1111111000111000";
    constant ap_const_lv16_113 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100010011";
    constant ap_const_lv16_FF04 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100000100";
    constant ap_const_lv16_FEB2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111010110010";
    constant ap_const_lv16_FF97 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110010111";
    constant ap_const_lv16_FF84 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000100";
    constant ap_const_lv16_41 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000001";
    constant ap_const_lv16_FFC4 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111000100";
    constant ap_const_lv16_6E : STD_LOGIC_VECTOR (15 downto 0) := "0000000001101110";
    constant ap_const_lv16_FF6E : STD_LOGIC_VECTOR (15 downto 0) := "1111111101101110";
    constant ap_const_lv16_FF30 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100110000";
    constant ap_const_lv16_FF7C : STD_LOGIC_VECTOR (15 downto 0) := "1111111101111100";
    constant ap_const_lv16_FFCF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111001111";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv16_FFF2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110010";
    constant ap_const_lv16_23 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100011";
    constant ap_const_lv16_63 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100011";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer26_out_blk_n : STD_LOGIC;
    signal layer24_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln28_fu_323_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_reg_1074 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln28_1_reg_1079 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_2_reg_1084 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_3_reg_1089 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_4_reg_1094 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_5_reg_1099 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_6_reg_1104 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_7_reg_1109 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_8_reg_1114 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_9_reg_1119 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_s_reg_1124 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_10_reg_1129 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_11_reg_1134 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_12_reg_1139 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_13_reg_1144 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_14_reg_1149 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_15_reg_1154 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_16_reg_1159 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_17_reg_1164 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_18_reg_1169 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_19_reg_1174 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_20_reg_1179 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_21_reg_1184 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_22_reg_1189 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_23_reg_1194 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_24_reg_1199 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_25_reg_1204 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_26_reg_1209 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_27_reg_1214 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_28_reg_1219 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_29_reg_1224 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_30_reg_1229 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_31_reg_1234 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_32_reg_1239 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_33_reg_1244 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_34_reg_1249 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_35_reg_1254 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_36_reg_1259 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_37_reg_1264 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_38_reg_1269 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_39_reg_1274 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_40_reg_1279 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_41_reg_1284 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_42_reg_1289 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_43_reg_1294 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_44_reg_1299 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_45_reg_1304 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_fu_787_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_reg_1309 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln42_1_fu_792_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_1_reg_1314 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_2_fu_797_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_2_reg_1319 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_3_fu_802_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_3_reg_1324 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_4_fu_807_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_4_reg_1329 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_5_fu_812_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_5_reg_1334 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_6_fu_817_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_6_reg_1339 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_7_fu_822_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_7_reg_1344 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_8_fu_827_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_8_reg_1349 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_9_fu_832_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_9_reg_1354 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_10_fu_837_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_10_reg_1359 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_11_fu_842_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_11_reg_1364 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_12_fu_847_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_12_reg_1369 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_13_fu_852_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_13_reg_1374 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_14_fu_857_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_14_reg_1379 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_15_fu_862_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_15_reg_1384 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_16_fu_867_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_16_reg_1389 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_17_fu_872_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_17_reg_1394 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_18_fu_877_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_18_reg_1399 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_19_fu_882_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_19_reg_1404 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_20_fu_887_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_20_reg_1409 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_21_fu_892_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_21_reg_1414 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_22_fu_897_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_22_reg_1419 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_23_fu_902_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_23_reg_1424 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_24_fu_907_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_24_reg_1429 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_25_fu_912_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_25_reg_1434 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_26_fu_917_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_26_reg_1439 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_27_fu_922_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_27_reg_1444 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_28_fu_927_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_28_reg_1449 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_29_fu_932_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_29_reg_1454 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_30_fu_937_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_30_reg_1459 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_31_fu_942_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_31_reg_1464 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_32_fu_947_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_32_reg_1469 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_33_fu_952_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_33_reg_1474 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_34_fu_957_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_34_reg_1479 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_35_fu_962_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_35_reg_1484 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_36_fu_967_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_36_reg_1489 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_37_fu_972_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_37_reg_1494 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_38_fu_977_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_38_reg_1499 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_39_fu_982_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_39_reg_1504 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_40_fu_987_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_40_reg_1509 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_41_fu_992_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_41_reg_1514 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_42_fu_997_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_42_reg_1519 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_43_fu_1002_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_43_reg_1524 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_44_fu_1007_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_44_reg_1529 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_45_fu_1012_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_45_reg_1534 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_46_fu_1017_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_46_reg_1539 : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_layer24_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state4 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal layer24_out_TDATA_int_regslice : STD_LOGIC_VECTOR (751 downto 0);
    signal layer24_out_TVALID_int_regslice : STD_LOGIC;
    signal layer24_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_layer24_out_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_layer24_out_U : component myproject_regslice_both
    generic map (
        DataWidth => 752)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => layer24_out_TDATA_int_regslice,
        vld_in => layer24_out_TVALID_int_regslice,
        ack_in => layer24_out_TREADY_int_regslice,
        data_out => layer24_out_TDATA,
        vld_out => regslice_both_layer24_out_U_vld_out,
        ack_out => layer24_out_TREADY,
        apdone_blk => regslice_both_layer24_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln42_10_reg_1359 <= add_ln42_10_fu_837_p2;
                add_ln42_11_reg_1364 <= add_ln42_11_fu_842_p2;
                add_ln42_12_reg_1369 <= add_ln42_12_fu_847_p2;
                add_ln42_13_reg_1374 <= add_ln42_13_fu_852_p2;
                add_ln42_14_reg_1379 <= add_ln42_14_fu_857_p2;
                add_ln42_15_reg_1384 <= add_ln42_15_fu_862_p2;
                add_ln42_16_reg_1389 <= add_ln42_16_fu_867_p2;
                add_ln42_17_reg_1394 <= add_ln42_17_fu_872_p2;
                add_ln42_18_reg_1399 <= add_ln42_18_fu_877_p2;
                add_ln42_19_reg_1404 <= add_ln42_19_fu_882_p2;
                add_ln42_1_reg_1314 <= add_ln42_1_fu_792_p2;
                add_ln42_20_reg_1409 <= add_ln42_20_fu_887_p2;
                add_ln42_21_reg_1414 <= add_ln42_21_fu_892_p2;
                add_ln42_22_reg_1419 <= add_ln42_22_fu_897_p2;
                add_ln42_23_reg_1424 <= add_ln42_23_fu_902_p2;
                add_ln42_24_reg_1429 <= add_ln42_24_fu_907_p2;
                add_ln42_25_reg_1434 <= add_ln42_25_fu_912_p2;
                add_ln42_26_reg_1439 <= add_ln42_26_fu_917_p2;
                add_ln42_27_reg_1444 <= add_ln42_27_fu_922_p2;
                add_ln42_28_reg_1449 <= add_ln42_28_fu_927_p2;
                add_ln42_29_reg_1454 <= add_ln42_29_fu_932_p2;
                add_ln42_2_reg_1319 <= add_ln42_2_fu_797_p2;
                add_ln42_30_reg_1459 <= add_ln42_30_fu_937_p2;
                add_ln42_31_reg_1464 <= add_ln42_31_fu_942_p2;
                add_ln42_32_reg_1469 <= add_ln42_32_fu_947_p2;
                add_ln42_33_reg_1474 <= add_ln42_33_fu_952_p2;
                add_ln42_34_reg_1479 <= add_ln42_34_fu_957_p2;
                add_ln42_35_reg_1484 <= add_ln42_35_fu_962_p2;
                add_ln42_36_reg_1489 <= add_ln42_36_fu_967_p2;
                add_ln42_37_reg_1494 <= add_ln42_37_fu_972_p2;
                add_ln42_38_reg_1499 <= add_ln42_38_fu_977_p2;
                add_ln42_39_reg_1504 <= add_ln42_39_fu_982_p2;
                add_ln42_3_reg_1324 <= add_ln42_3_fu_802_p2;
                add_ln42_40_reg_1509 <= add_ln42_40_fu_987_p2;
                add_ln42_41_reg_1514 <= add_ln42_41_fu_992_p2;
                add_ln42_42_reg_1519 <= add_ln42_42_fu_997_p2;
                add_ln42_43_reg_1524 <= add_ln42_43_fu_1002_p2;
                add_ln42_44_reg_1529 <= add_ln42_44_fu_1007_p2;
                add_ln42_45_reg_1534 <= add_ln42_45_fu_1012_p2;
                add_ln42_46_reg_1539 <= add_ln42_46_fu_1017_p2;
                add_ln42_4_reg_1329 <= add_ln42_4_fu_807_p2;
                add_ln42_5_reg_1334 <= add_ln42_5_fu_812_p2;
                add_ln42_6_reg_1339 <= add_ln42_6_fu_817_p2;
                add_ln42_7_reg_1344 <= add_ln42_7_fu_822_p2;
                add_ln42_8_reg_1349 <= add_ln42_8_fu_827_p2;
                add_ln42_9_reg_1354 <= add_ln42_9_fu_832_p2;
                add_ln42_reg_1309 <= add_ln42_fu_787_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_ln28_10_reg_1129 <= layer26_out_dout(191 downto 176);
                trunc_ln28_11_reg_1134 <= layer26_out_dout(207 downto 192);
                trunc_ln28_12_reg_1139 <= layer26_out_dout(223 downto 208);
                trunc_ln28_13_reg_1144 <= layer26_out_dout(239 downto 224);
                trunc_ln28_14_reg_1149 <= layer26_out_dout(255 downto 240);
                trunc_ln28_15_reg_1154 <= layer26_out_dout(271 downto 256);
                trunc_ln28_16_reg_1159 <= layer26_out_dout(287 downto 272);
                trunc_ln28_17_reg_1164 <= layer26_out_dout(303 downto 288);
                trunc_ln28_18_reg_1169 <= layer26_out_dout(319 downto 304);
                trunc_ln28_19_reg_1174 <= layer26_out_dout(335 downto 320);
                trunc_ln28_1_reg_1079 <= layer26_out_dout(31 downto 16);
                trunc_ln28_20_reg_1179 <= layer26_out_dout(351 downto 336);
                trunc_ln28_21_reg_1184 <= layer26_out_dout(367 downto 352);
                trunc_ln28_22_reg_1189 <= layer26_out_dout(383 downto 368);
                trunc_ln28_23_reg_1194 <= layer26_out_dout(399 downto 384);
                trunc_ln28_24_reg_1199 <= layer26_out_dout(415 downto 400);
                trunc_ln28_25_reg_1204 <= layer26_out_dout(431 downto 416);
                trunc_ln28_26_reg_1209 <= layer26_out_dout(447 downto 432);
                trunc_ln28_27_reg_1214 <= layer26_out_dout(463 downto 448);
                trunc_ln28_28_reg_1219 <= layer26_out_dout(479 downto 464);
                trunc_ln28_29_reg_1224 <= layer26_out_dout(495 downto 480);
                trunc_ln28_2_reg_1084 <= layer26_out_dout(47 downto 32);
                trunc_ln28_30_reg_1229 <= layer26_out_dout(511 downto 496);
                trunc_ln28_31_reg_1234 <= layer26_out_dout(527 downto 512);
                trunc_ln28_32_reg_1239 <= layer26_out_dout(543 downto 528);
                trunc_ln28_33_reg_1244 <= layer26_out_dout(559 downto 544);
                trunc_ln28_34_reg_1249 <= layer26_out_dout(575 downto 560);
                trunc_ln28_35_reg_1254 <= layer26_out_dout(591 downto 576);
                trunc_ln28_36_reg_1259 <= layer26_out_dout(607 downto 592);
                trunc_ln28_37_reg_1264 <= layer26_out_dout(623 downto 608);
                trunc_ln28_38_reg_1269 <= layer26_out_dout(639 downto 624);
                trunc_ln28_39_reg_1274 <= layer26_out_dout(655 downto 640);
                trunc_ln28_3_reg_1089 <= layer26_out_dout(63 downto 48);
                trunc_ln28_40_reg_1279 <= layer26_out_dout(671 downto 656);
                trunc_ln28_41_reg_1284 <= layer26_out_dout(687 downto 672);
                trunc_ln28_42_reg_1289 <= layer26_out_dout(703 downto 688);
                trunc_ln28_43_reg_1294 <= layer26_out_dout(719 downto 704);
                trunc_ln28_44_reg_1299 <= layer26_out_dout(735 downto 720);
                trunc_ln28_45_reg_1304 <= layer26_out_dout(751 downto 736);
                trunc_ln28_4_reg_1094 <= layer26_out_dout(79 downto 64);
                trunc_ln28_5_reg_1099 <= layer26_out_dout(95 downto 80);
                trunc_ln28_6_reg_1104 <= layer26_out_dout(111 downto 96);
                trunc_ln28_7_reg_1109 <= layer26_out_dout(127 downto 112);
                trunc_ln28_8_reg_1114 <= layer26_out_dout(143 downto 128);
                trunc_ln28_9_reg_1119 <= layer26_out_dout(159 downto 144);
                trunc_ln28_reg_1074 <= trunc_ln28_fu_323_p1;
                trunc_ln28_s_reg_1124 <= layer26_out_dout(175 downto 160);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state1, ap_block_state4, layer24_out_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer24_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln42_10_fu_837_p2 <= std_logic_vector(unsigned(trunc_ln28_s_reg_1124) + unsigned(ap_const_lv16_26));
    add_ln42_11_fu_842_p2 <= std_logic_vector(unsigned(trunc_ln28_10_reg_1129) + unsigned(ap_const_lv16_FF8C));
    add_ln42_12_fu_847_p2 <= std_logic_vector(unsigned(trunc_ln28_11_reg_1134) + unsigned(ap_const_lv16_C3));
    add_ln42_13_fu_852_p2 <= std_logic_vector(unsigned(trunc_ln28_12_reg_1139) + unsigned(ap_const_lv16_FF34));
    add_ln42_14_fu_857_p2 <= std_logic_vector(unsigned(trunc_ln28_13_reg_1144) + unsigned(ap_const_lv16_112));
    add_ln42_15_fu_862_p2 <= std_logic_vector(unsigned(trunc_ln28_14_reg_1149) + unsigned(ap_const_lv16_73));
    add_ln42_16_fu_867_p2 <= std_logic_vector(unsigned(trunc_ln28_15_reg_1154) + unsigned(ap_const_lv16_FF81));
    add_ln42_17_fu_872_p2 <= std_logic_vector(unsigned(trunc_ln28_16_reg_1159) + unsigned(ap_const_lv16_60));
    add_ln42_18_fu_877_p2 <= std_logic_vector(unsigned(trunc_ln28_17_reg_1164) + unsigned(ap_const_lv16_5C));
    add_ln42_19_fu_882_p2 <= std_logic_vector(unsigned(trunc_ln28_18_reg_1169) + unsigned(ap_const_lv16_FFDE));
    add_ln42_1_fu_792_p2 <= std_logic_vector(unsigned(trunc_ln28_1_reg_1079) + unsigned(ap_const_lv16_FF4B));
    add_ln42_20_fu_887_p2 <= std_logic_vector(unsigned(trunc_ln28_19_reg_1174) + unsigned(ap_const_lv16_58));
    add_ln42_21_fu_892_p2 <= std_logic_vector(unsigned(trunc_ln28_20_reg_1179) + unsigned(ap_const_lv16_8F));
    add_ln42_22_fu_897_p2 <= std_logic_vector(unsigned(trunc_ln28_21_reg_1184) + unsigned(ap_const_lv16_8F));
    add_ln42_23_fu_902_p2 <= std_logic_vector(unsigned(trunc_ln28_22_reg_1189) + unsigned(ap_const_lv16_FF55));
    add_ln42_24_fu_907_p2 <= std_logic_vector(unsigned(trunc_ln28_23_reg_1194) + unsigned(ap_const_lv16_E8));
    add_ln42_25_fu_912_p2 <= std_logic_vector(unsigned(trunc_ln28_24_reg_1199) + unsigned(ap_const_lv16_3A));
    add_ln42_26_fu_917_p2 <= std_logic_vector(unsigned(trunc_ln28_25_reg_1204) + unsigned(ap_const_lv16_FEE2));
    add_ln42_27_fu_922_p2 <= std_logic_vector(unsigned(trunc_ln28_26_reg_1209) + unsigned(ap_const_lv16_FFD1));
    add_ln42_28_fu_927_p2 <= std_logic_vector(unsigned(trunc_ln28_27_reg_1214) + unsigned(ap_const_lv16_17));
    add_ln42_29_fu_932_p2 <= std_logic_vector(unsigned(trunc_ln28_28_reg_1219) + unsigned(ap_const_lv16_61));
    add_ln42_2_fu_797_p2 <= std_logic_vector(unsigned(trunc_ln28_2_reg_1084) + unsigned(ap_const_lv16_3E));
    add_ln42_30_fu_937_p2 <= std_logic_vector(unsigned(trunc_ln28_29_reg_1224) + unsigned(ap_const_lv16_FE38));
    add_ln42_31_fu_942_p2 <= std_logic_vector(unsigned(trunc_ln28_30_reg_1229) + unsigned(ap_const_lv16_113));
    add_ln42_32_fu_947_p2 <= std_logic_vector(unsigned(trunc_ln28_31_reg_1234) + unsigned(ap_const_lv16_FF04));
    add_ln42_33_fu_952_p2 <= std_logic_vector(unsigned(trunc_ln28_32_reg_1239) + unsigned(ap_const_lv16_FEB2));
    add_ln42_34_fu_957_p2 <= std_logic_vector(unsigned(trunc_ln28_33_reg_1244) + unsigned(ap_const_lv16_FF97));
    add_ln42_35_fu_962_p2 <= std_logic_vector(unsigned(trunc_ln28_34_reg_1249) + unsigned(ap_const_lv16_FF84));
    add_ln42_36_fu_967_p2 <= std_logic_vector(unsigned(trunc_ln28_35_reg_1254) + unsigned(ap_const_lv16_41));
    add_ln42_37_fu_972_p2 <= std_logic_vector(unsigned(trunc_ln28_36_reg_1259) + unsigned(ap_const_lv16_FFC4));
    add_ln42_38_fu_977_p2 <= std_logic_vector(unsigned(trunc_ln28_37_reg_1264) + unsigned(ap_const_lv16_6E));
    add_ln42_39_fu_982_p2 <= std_logic_vector(unsigned(trunc_ln28_38_reg_1269) + unsigned(ap_const_lv16_FF6E));
    add_ln42_3_fu_802_p2 <= std_logic_vector(unsigned(trunc_ln28_3_reg_1089) + unsigned(ap_const_lv16_14));
    add_ln42_40_fu_987_p2 <= std_logic_vector(unsigned(trunc_ln28_39_reg_1274) + unsigned(ap_const_lv16_FF30));
    add_ln42_41_fu_992_p2 <= std_logic_vector(unsigned(trunc_ln28_40_reg_1279) + unsigned(ap_const_lv16_FF7C));
    add_ln42_42_fu_997_p2 <= std_logic_vector(unsigned(trunc_ln28_41_reg_1284) + unsigned(ap_const_lv16_FFCF));
    add_ln42_43_fu_1002_p2 <= std_logic_vector(unsigned(trunc_ln28_42_reg_1289) + unsigned(ap_const_lv16_2));
    add_ln42_44_fu_1007_p2 <= std_logic_vector(unsigned(trunc_ln28_43_reg_1294) + unsigned(ap_const_lv16_FFF2));
    add_ln42_45_fu_1012_p2 <= std_logic_vector(unsigned(trunc_ln28_44_reg_1299) + unsigned(ap_const_lv16_23));
    add_ln42_46_fu_1017_p2 <= std_logic_vector(unsigned(trunc_ln28_45_reg_1304) + unsigned(ap_const_lv16_63));
    add_ln42_4_fu_807_p2 <= std_logic_vector(unsigned(trunc_ln28_4_reg_1094) + unsigned(ap_const_lv16_FFDC));
    add_ln42_5_fu_812_p2 <= std_logic_vector(unsigned(trunc_ln28_5_reg_1099) + unsigned(ap_const_lv16_4A));
    add_ln42_6_fu_817_p2 <= std_logic_vector(unsigned(trunc_ln28_6_reg_1104) + unsigned(ap_const_lv16_6B));
    add_ln42_7_fu_822_p2 <= std_logic_vector(unsigned(trunc_ln28_7_reg_1109) + unsigned(ap_const_lv16_FFCC));
    add_ln42_8_fu_827_p2 <= std_logic_vector(unsigned(trunc_ln28_8_reg_1114) + unsigned(ap_const_lv16_FFF8));
    add_ln42_9_fu_832_p2 <= std_logic_vector(unsigned(trunc_ln28_9_reg_1119) + unsigned(ap_const_lv16_70));
    add_ln42_fu_787_p2 <= std_logic_vector(unsigned(trunc_ln28_reg_1074) + unsigned(ap_const_lv16_10));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer24_out_TREADY_int_regslice)
    begin
        if ((layer24_out_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, layer26_out_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (layer26_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state4_assign_proc : process(regslice_both_layer24_out_U_apdone_blk, layer24_out_TREADY_int_regslice)
    begin
                ap_block_state4 <= ((layer24_out_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_layer24_out_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer24_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, layer24_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer24_out_TDATA_blk_n <= layer24_out_TREADY_int_regslice;
        else 
            layer24_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer24_out_TDATA_int_regslice <= ((((((((((((((((((((((((((((((((((((((((((((((add_ln42_46_reg_1539 & add_ln42_45_reg_1534) & add_ln42_44_reg_1529) & add_ln42_43_reg_1524) & add_ln42_42_reg_1519) & add_ln42_41_reg_1514) & add_ln42_40_reg_1509) & add_ln42_39_reg_1504) & add_ln42_38_reg_1499) & add_ln42_37_reg_1494) & add_ln42_36_reg_1489) & add_ln42_35_reg_1484) & add_ln42_34_reg_1479) & add_ln42_33_reg_1474) & add_ln42_32_reg_1469) & add_ln42_31_reg_1464) & add_ln42_30_reg_1459) & add_ln42_29_reg_1454) & add_ln42_28_reg_1449) & add_ln42_27_reg_1444) & add_ln42_26_reg_1439) & add_ln42_25_reg_1434) & add_ln42_24_reg_1429) & add_ln42_23_reg_1424) & add_ln42_22_reg_1419) & add_ln42_21_reg_1414) & add_ln42_20_reg_1409) & add_ln42_19_reg_1404) & add_ln42_18_reg_1399) & add_ln42_17_reg_1394) & add_ln42_16_reg_1389) & add_ln42_15_reg_1384) & add_ln42_14_reg_1379) & add_ln42_13_reg_1374) & add_ln42_12_reg_1369) & add_ln42_11_reg_1364) & add_ln42_10_reg_1359) & add_ln42_9_reg_1354) & add_ln42_8_reg_1349) & add_ln42_7_reg_1344) & add_ln42_6_reg_1339) & 
    add_ln42_5_reg_1334) & add_ln42_4_reg_1329) & add_ln42_3_reg_1324) & add_ln42_2_reg_1319) & add_ln42_1_reg_1314) & add_ln42_reg_1309);
    layer24_out_TVALID <= regslice_both_layer24_out_U_vld_out;

    layer24_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state3, layer24_out_TREADY_int_regslice)
    begin
        if (((layer24_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer24_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            layer24_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    layer26_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer26_out_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer26_out_blk_n <= layer26_out_empty_n;
        else 
            layer26_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer26_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer26_out_read <= ap_const_logic_1;
        else 
            layer26_out_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln28_fu_323_p1 <= layer26_out_dout(16 - 1 downto 0);
end behav;
