-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer25_out_dout : IN STD_LOGIC_VECTOR (383 downto 0);
    layer25_out_empty_n : IN STD_LOGIC;
    layer25_out_read : OUT STD_LOGIC;
    layer25_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer25_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer23_out_din : OUT STD_LOGIC_VECTOR (383 downto 0);
    layer23_out_full_n : IN STD_LOGIC;
    layer23_out_write : OUT STD_LOGIC;
    layer23_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer23_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv16_11F : STD_LOGIC_VECTOR (15 downto 0) := "0000000100011111";
    constant ap_const_lv16_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_const_lv16_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010001";
    constant ap_const_lv16_FFEC : STD_LOGIC_VECTOR (15 downto 0) := "1111111111101100";
    constant ap_const_lv16_FD96 : STD_LOGIC_VECTOR (15 downto 0) := "1111110110010110";
    constant ap_const_lv16_FE34 : STD_LOGIC_VECTOR (15 downto 0) := "1111111000110100";
    constant ap_const_lv16_FFBE : STD_LOGIC_VECTOR (15 downto 0) := "1111111110111110";
    constant ap_const_lv16_FF23 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100100011";
    constant ap_const_lv16_FF91 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110010001";
    constant ap_const_lv16_273 : STD_LOGIC_VECTOR (15 downto 0) := "0000001001110011";
    constant ap_const_lv16_FF42 : STD_LOGIC_VECTOR (15 downto 0) := "1111111101000010";
    constant ap_const_lv16_FFC5 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111000101";
    constant ap_const_lv16_D5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011010101";
    constant ap_const_lv16_FF5C : STD_LOGIC_VECTOR (15 downto 0) := "1111111101011100";
    constant ap_const_lv16_11A : STD_LOGIC_VECTOR (15 downto 0) := "0000000100011010";
    constant ap_const_lv16_21 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100001";
    constant ap_const_lv16_FFBA : STD_LOGIC_VECTOR (15 downto 0) := "1111111110111010";
    constant ap_const_lv16_26 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100110";
    constant ap_const_lv16_FEC1 : STD_LOGIC_VECTOR (15 downto 0) := "1111111011000001";
    constant ap_const_lv16_1C8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000111001000";
    constant ap_const_lv16_5A : STD_LOGIC_VECTOR (15 downto 0) := "0000000001011010";
    constant ap_const_lv16_1BA : STD_LOGIC_VECTOR (15 downto 0) := "0000000110111010";
    constant ap_const_lv16_248 : STD_LOGIC_VECTOR (15 downto 0) := "0000001001001000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer25_out_blk_n : STD_LOGIC;
    signal layer23_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln28_fu_179_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_reg_557 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln28_s_reg_562 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_46_reg_567 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_47_reg_572 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_48_reg_577 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_49_reg_582 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_50_reg_587 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_51_reg_592 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_52_reg_597 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_53_reg_602 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_54_reg_607 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_55_reg_612 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_56_reg_617 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_57_reg_622 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_58_reg_627 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_59_reg_632 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_60_reg_637 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_61_reg_642 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_62_reg_647 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_63_reg_652 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_64_reg_657 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_65_reg_662 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_66_reg_667 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_67_reg_672 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_fu_413_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_reg_677 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln42_47_fu_418_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_47_reg_682 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_48_fu_423_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_48_reg_687 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_49_fu_428_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_49_reg_692 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_50_fu_433_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_50_reg_697 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_51_fu_438_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_51_reg_702 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_52_fu_443_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_52_reg_707 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_53_fu_448_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_53_reg_712 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_54_fu_453_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_54_reg_717 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_55_fu_458_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_55_reg_722 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_56_fu_463_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_56_reg_727 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_57_fu_468_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_57_reg_732 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_58_fu_473_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_58_reg_737 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_59_fu_478_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_59_reg_742 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_60_fu_483_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_60_reg_747 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_61_fu_488_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_61_reg_752 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_62_fu_493_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_62_reg_757 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_63_fu_498_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_63_reg_762 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_64_fu_503_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_64_reg_767 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_65_fu_508_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_65_reg_772 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_66_fu_513_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_66_reg_777 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_67_fu_518_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_67_reg_782 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_68_fu_523_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_68_reg_787 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln42_47_reg_682 <= add_ln42_47_fu_418_p2;
                add_ln42_48_reg_687 <= add_ln42_48_fu_423_p2;
                add_ln42_49_reg_692 <= add_ln42_49_fu_428_p2;
                add_ln42_50_reg_697 <= add_ln42_50_fu_433_p2;
                add_ln42_51_reg_702 <= add_ln42_51_fu_438_p2;
                add_ln42_52_reg_707 <= add_ln42_52_fu_443_p2;
                add_ln42_53_reg_712 <= add_ln42_53_fu_448_p2;
                add_ln42_54_reg_717 <= add_ln42_54_fu_453_p2;
                add_ln42_55_reg_722 <= add_ln42_55_fu_458_p2;
                add_ln42_56_reg_727 <= add_ln42_56_fu_463_p2;
                add_ln42_57_reg_732 <= add_ln42_57_fu_468_p2;
                add_ln42_58_reg_737 <= add_ln42_58_fu_473_p2;
                add_ln42_59_reg_742 <= add_ln42_59_fu_478_p2;
                add_ln42_60_reg_747 <= add_ln42_60_fu_483_p2;
                add_ln42_61_reg_752 <= add_ln42_61_fu_488_p2;
                add_ln42_62_reg_757 <= add_ln42_62_fu_493_p2;
                add_ln42_63_reg_762 <= add_ln42_63_fu_498_p2;
                add_ln42_64_reg_767 <= add_ln42_64_fu_503_p2;
                add_ln42_65_reg_772 <= add_ln42_65_fu_508_p2;
                add_ln42_66_reg_777 <= add_ln42_66_fu_513_p2;
                add_ln42_67_reg_782 <= add_ln42_67_fu_518_p2;
                add_ln42_68_reg_787 <= add_ln42_68_fu_523_p2;
                add_ln42_reg_677 <= add_ln42_fu_413_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_ln28_46_reg_567 <= layer25_out_dout(47 downto 32);
                trunc_ln28_47_reg_572 <= layer25_out_dout(63 downto 48);
                trunc_ln28_48_reg_577 <= layer25_out_dout(79 downto 64);
                trunc_ln28_49_reg_582 <= layer25_out_dout(95 downto 80);
                trunc_ln28_50_reg_587 <= layer25_out_dout(111 downto 96);
                trunc_ln28_51_reg_592 <= layer25_out_dout(127 downto 112);
                trunc_ln28_52_reg_597 <= layer25_out_dout(143 downto 128);
                trunc_ln28_53_reg_602 <= layer25_out_dout(159 downto 144);
                trunc_ln28_54_reg_607 <= layer25_out_dout(175 downto 160);
                trunc_ln28_55_reg_612 <= layer25_out_dout(191 downto 176);
                trunc_ln28_56_reg_617 <= layer25_out_dout(207 downto 192);
                trunc_ln28_57_reg_622 <= layer25_out_dout(223 downto 208);
                trunc_ln28_58_reg_627 <= layer25_out_dout(239 downto 224);
                trunc_ln28_59_reg_632 <= layer25_out_dout(255 downto 240);
                trunc_ln28_60_reg_637 <= layer25_out_dout(271 downto 256);
                trunc_ln28_61_reg_642 <= layer25_out_dout(287 downto 272);
                trunc_ln28_62_reg_647 <= layer25_out_dout(303 downto 288);
                trunc_ln28_63_reg_652 <= layer25_out_dout(319 downto 304);
                trunc_ln28_64_reg_657 <= layer25_out_dout(335 downto 320);
                trunc_ln28_65_reg_662 <= layer25_out_dout(351 downto 336);
                trunc_ln28_66_reg_667 <= layer25_out_dout(367 downto 352);
                trunc_ln28_67_reg_672 <= layer25_out_dout(383 downto 368);
                trunc_ln28_reg_557 <= trunc_ln28_fu_179_p1;
                trunc_ln28_s_reg_562 <= layer25_out_dout(31 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer23_out_full_n, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln42_47_fu_418_p2 <= std_logic_vector(unsigned(trunc_ln28_s_reg_562) + unsigned(ap_const_lv16_8));
    add_ln42_48_fu_423_p2 <= std_logic_vector(unsigned(trunc_ln28_46_reg_567) + unsigned(ap_const_lv16_11));
    add_ln42_49_fu_428_p2 <= std_logic_vector(unsigned(trunc_ln28_47_reg_572) + unsigned(ap_const_lv16_FFEC));
    add_ln42_50_fu_433_p2 <= std_logic_vector(unsigned(trunc_ln28_48_reg_577) + unsigned(ap_const_lv16_FD96));
    add_ln42_51_fu_438_p2 <= std_logic_vector(unsigned(trunc_ln28_49_reg_582) + unsigned(ap_const_lv16_FE34));
    add_ln42_52_fu_443_p2 <= std_logic_vector(unsigned(trunc_ln28_50_reg_587) + unsigned(ap_const_lv16_FFBE));
    add_ln42_53_fu_448_p2 <= std_logic_vector(unsigned(trunc_ln28_51_reg_592) + unsigned(ap_const_lv16_FF23));
    add_ln42_54_fu_453_p2 <= std_logic_vector(unsigned(trunc_ln28_53_reg_602) + unsigned(ap_const_lv16_FF91));
    add_ln42_55_fu_458_p2 <= std_logic_vector(unsigned(trunc_ln28_54_reg_607) + unsigned(ap_const_lv16_273));
    add_ln42_56_fu_463_p2 <= std_logic_vector(unsigned(trunc_ln28_55_reg_612) + unsigned(ap_const_lv16_FF42));
    add_ln42_57_fu_468_p2 <= std_logic_vector(unsigned(trunc_ln28_56_reg_617) + unsigned(ap_const_lv16_FFC5));
    add_ln42_58_fu_473_p2 <= std_logic_vector(unsigned(trunc_ln28_57_reg_622) + unsigned(ap_const_lv16_D5));
    add_ln42_59_fu_478_p2 <= std_logic_vector(unsigned(trunc_ln28_58_reg_627) + unsigned(ap_const_lv16_FF5C));
    add_ln42_60_fu_483_p2 <= std_logic_vector(unsigned(trunc_ln28_59_reg_632) + unsigned(ap_const_lv16_11A));
    add_ln42_61_fu_488_p2 <= std_logic_vector(unsigned(trunc_ln28_60_reg_637) + unsigned(ap_const_lv16_21));
    add_ln42_62_fu_493_p2 <= std_logic_vector(unsigned(trunc_ln28_61_reg_642) + unsigned(ap_const_lv16_FFBA));
    add_ln42_63_fu_498_p2 <= std_logic_vector(unsigned(trunc_ln28_62_reg_647) + unsigned(ap_const_lv16_26));
    add_ln42_64_fu_503_p2 <= std_logic_vector(unsigned(trunc_ln28_63_reg_652) + unsigned(ap_const_lv16_FEC1));
    add_ln42_65_fu_508_p2 <= std_logic_vector(unsigned(trunc_ln28_64_reg_657) + unsigned(ap_const_lv16_1C8));
    add_ln42_66_fu_513_p2 <= std_logic_vector(unsigned(trunc_ln28_65_reg_662) + unsigned(ap_const_lv16_5A));
    add_ln42_67_fu_518_p2 <= std_logic_vector(unsigned(trunc_ln28_66_reg_667) + unsigned(ap_const_lv16_1BA));
    add_ln42_68_fu_523_p2 <= std_logic_vector(unsigned(trunc_ln28_67_reg_672) + unsigned(ap_const_lv16_248));
    add_ln42_fu_413_p2 <= std_logic_vector(unsigned(trunc_ln28_reg_557) + unsigned(ap_const_lv16_11F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer23_out_full_n)
    begin
        if ((layer23_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer25_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer25_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer23_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    internal_ap_ready_assign_proc : process(layer23_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer23_out_blk_n_assign_proc : process(layer23_out_full_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer23_out_blk_n <= layer23_out_full_n;
        else 
            layer23_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer23_out_din <= (((((((((((((((((((((((add_ln42_68_reg_787 & add_ln42_67_reg_782) & add_ln42_66_reg_777) & add_ln42_65_reg_772) & add_ln42_64_reg_767) & add_ln42_63_reg_762) & add_ln42_62_reg_757) & add_ln42_61_reg_752) & add_ln42_60_reg_747) & add_ln42_59_reg_742) & add_ln42_58_reg_737) & add_ln42_57_reg_732) & add_ln42_56_reg_727) & add_ln42_55_reg_722) & add_ln42_54_reg_717) & trunc_ln28_52_reg_597) & add_ln42_53_reg_712) & add_ln42_52_reg_707) & add_ln42_51_reg_702) & add_ln42_50_reg_697) & add_ln42_49_reg_692) & add_ln42_48_reg_687) & add_ln42_47_reg_682) & add_ln42_reg_677);

    layer23_out_write_assign_proc : process(layer23_out_full_n, ap_CS_fsm_state3)
    begin
        if (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer23_out_write <= ap_const_logic_1;
        else 
            layer23_out_write <= ap_const_logic_0;
        end if; 
    end process;


    layer25_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer25_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer25_out_blk_n <= layer25_out_empty_n;
        else 
            layer25_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer25_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer25_out_read <= ap_const_logic_1;
        else 
            layer25_out_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln28_fu_179_p1 <= layer25_out_dout(16 - 1 downto 0);
end behav;
