-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    global_in_TDATA : IN STD_LOGIC_VECTOR (447 downto 0);
    layer24_out_TDATA : OUT STD_LOGIC_VECTOR (751 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    global_in_TVALID : IN STD_LOGIC;
    global_in_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    layer24_out_TVALID : OUT STD_LOGIC;
    layer24_out_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject_myproject,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-ftg256-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=12.557208,HLS_SYN_LAT=50432,HLS_SYN_TPT=17747,HLS_SYN_MEM=51,HLS_SYN_DSP=0,HLS_SYN_FF=39333,HLS_SYN_LUT=28037,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_start : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_done : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_continue : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_idle : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_ready : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_start_out : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_start_write : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_global_in_TREADY : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_din : STD_LOGIC_VECTOR (15 downto 0);
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_write : STD_LOGIC;
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer10_out_read : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer27_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer27_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_start_write : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer27_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_start : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_done : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_continue : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_idle : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_ready : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_start_out : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer12_out_read : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer13_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer13_out_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer13_out_read : STD_LOGIC;
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer28_out_din : STD_LOGIC_VECTOR (127 downto 0);
    signal conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer28_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer28_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_din : STD_LOGIC_VECTOR (127 downto 0);
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_start : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_done : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_continue : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_idle : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_ready : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_start_out : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer15_out_read : STD_LOGIC;
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer16_out_din : STD_LOGIC_VECTOR (127 downto 0);
    signal pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer16_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer16_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer25_out_din : STD_LOGIC_VECTOR (383 downto 0);
    signal dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer25_out_write : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_start : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_done : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_continue : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_idle : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_ready : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_start_out : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_start_write : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer25_out_read : STD_LOGIC;
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer23_out_din : STD_LOGIC_VECTOR (383 downto 0);
    signal normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer23_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_start_write : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer23_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer20_out_din : STD_LOGIC_VECTOR (383 downto 0);
    signal relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer20_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer20_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer26_out_din : STD_LOGIC_VECTOR (751 downto 0);
    signal dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer26_out_write : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_start : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_done : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_continue : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_idle : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_ready : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer26_out_read : STD_LOGIC;
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer24_out_TDATA : STD_LOGIC_VECTOR (751 downto 0);
    signal normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer24_out_TVALID : STD_LOGIC;
    signal layer10_out_full_n : STD_LOGIC;
    signal layer10_out_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer10_out_empty_n : STD_LOGIC;
    signal layer10_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal layer10_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal layer27_out_full_n : STD_LOGIC;
    signal layer27_out_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal layer27_out_empty_n : STD_LOGIC;
    signal layer27_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal layer27_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal layer12_out_full_n : STD_LOGIC;
    signal layer12_out_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal layer12_out_empty_n : STD_LOGIC;
    signal layer12_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal layer12_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal layer13_out_full_n : STD_LOGIC;
    signal layer13_out_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal layer13_out_empty_n : STD_LOGIC;
    signal layer13_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer13_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer28_out_full_n : STD_LOGIC;
    signal layer28_out_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal layer28_out_empty_n : STD_LOGIC;
    signal layer28_out_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal layer28_out_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal layer15_out_full_n : STD_LOGIC;
    signal layer15_out_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal layer15_out_empty_n : STD_LOGIC;
    signal layer15_out_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal layer15_out_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal layer16_out_full_n : STD_LOGIC;
    signal layer16_out_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal layer16_out_empty_n : STD_LOGIC;
    signal layer16_out_num_data_valid : STD_LOGIC_VECTOR (5 downto 0);
    signal layer16_out_fifo_cap : STD_LOGIC_VECTOR (5 downto 0);
    signal layer25_out_full_n : STD_LOGIC;
    signal layer25_out_dout : STD_LOGIC_VECTOR (383 downto 0);
    signal layer25_out_empty_n : STD_LOGIC;
    signal layer25_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer25_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer23_out_full_n : STD_LOGIC;
    signal layer23_out_dout : STD_LOGIC_VECTOR (383 downto 0);
    signal layer23_out_empty_n : STD_LOGIC;
    signal layer23_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer23_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer20_out_full_n : STD_LOGIC;
    signal layer20_out_dout : STD_LOGIC_VECTOR (383 downto 0);
    signal layer20_out_empty_n : STD_LOGIC;
    signal layer20_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer20_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer26_out_full_n : STD_LOGIC;
    signal layer26_out_dout : STD_LOGIC_VECTOR (751 downto 0);
    signal layer26_out_empty_n : STD_LOGIC;
    signal layer26_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer26_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_full_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_empty_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_full_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_empty_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_full_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_empty_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_full_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_empty_n : STD_LOGIC;
    signal start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_full_n : STD_LOGIC;
    signal start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_empty_n : STD_LOGIC;
    signal start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_full_n : STD_LOGIC;
    signal start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_empty_n : STD_LOGIC;

    component myproject_transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        global_in_TDATA : IN STD_LOGIC_VECTOR (447 downto 0);
        global_in_TVALID : IN STD_LOGIC;
        global_in_TREADY : OUT STD_LOGIC;
        layer10_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer10_out_full_n : IN STD_LOGIC;
        layer10_out_write : OUT STD_LOGIC;
        layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer10_out_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        layer10_out_empty_n : IN STD_LOGIC;
        layer10_out_read : OUT STD_LOGIC;
        layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer27_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        layer27_out_full_n : IN STD_LOGIC;
        layer27_out_write : OUT STD_LOGIC;
        layer27_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer27_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer27_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        layer27_out_empty_n : IN STD_LOGIC;
        layer27_out_read : OUT STD_LOGIC;
        layer27_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer27_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer12_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        layer12_out_full_n : IN STD_LOGIC;
        layer12_out_write : OUT STD_LOGIC;
        layer12_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        layer12_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer12_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        layer12_out_empty_n : IN STD_LOGIC;
        layer12_out_read : OUT STD_LOGIC;
        layer12_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer12_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer13_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        layer13_out_full_n : IN STD_LOGIC;
        layer13_out_write : OUT STD_LOGIC;
        layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component myproject_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer13_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        layer13_out_empty_n : IN STD_LOGIC;
        layer13_out_read : OUT STD_LOGIC;
        layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer28_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        layer28_out_full_n : IN STD_LOGIC;
        layer28_out_write : OUT STD_LOGIC;
        layer28_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer28_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer28_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        layer28_out_empty_n : IN STD_LOGIC;
        layer28_out_read : OUT STD_LOGIC;
        layer28_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer28_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        layer15_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        layer15_out_full_n : IN STD_LOGIC;
        layer15_out_write : OUT STD_LOGIC;
        layer15_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        layer15_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer15_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        layer15_out_empty_n : IN STD_LOGIC;
        layer15_out_read : OUT STD_LOGIC;
        layer15_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer15_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        layer16_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        layer16_out_full_n : IN STD_LOGIC;
        layer16_out_write : OUT STD_LOGIC;
        layer16_out_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        layer16_out_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component myproject_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer16_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        layer16_out_empty_n : IN STD_LOGIC;
        layer16_out_read : OUT STD_LOGIC;
        layer16_out_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        layer16_out_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
        layer25_out_din : OUT STD_LOGIC_VECTOR (383 downto 0);
        layer25_out_full_n : IN STD_LOGIC;
        layer25_out_write : OUT STD_LOGIC;
        layer25_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer25_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component myproject_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer25_out_dout : IN STD_LOGIC_VECTOR (383 downto 0);
        layer25_out_empty_n : IN STD_LOGIC;
        layer25_out_read : OUT STD_LOGIC;
        layer25_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer25_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer23_out_din : OUT STD_LOGIC_VECTOR (383 downto 0);
        layer23_out_full_n : IN STD_LOGIC;
        layer23_out_write : OUT STD_LOGIC;
        layer23_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer23_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component myproject_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer23_out_dout : IN STD_LOGIC_VECTOR (383 downto 0);
        layer23_out_empty_n : IN STD_LOGIC;
        layer23_out_read : OUT STD_LOGIC;
        layer23_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer23_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer20_out_din : OUT STD_LOGIC_VECTOR (383 downto 0);
        layer20_out_full_n : IN STD_LOGIC;
        layer20_out_write : OUT STD_LOGIC;
        layer20_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer20_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component myproject_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer20_out_dout : IN STD_LOGIC_VECTOR (383 downto 0);
        layer20_out_empty_n : IN STD_LOGIC;
        layer20_out_read : OUT STD_LOGIC;
        layer20_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer20_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer26_out_din : OUT STD_LOGIC_VECTOR (751 downto 0);
        layer26_out_full_n : IN STD_LOGIC;
        layer26_out_write : OUT STD_LOGIC;
        layer26_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer26_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component myproject_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer26_out_dout : IN STD_LOGIC_VECTOR (751 downto 0);
        layer26_out_empty_n : IN STD_LOGIC;
        layer26_out_read : OUT STD_LOGIC;
        layer26_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer26_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer24_out_TDATA : OUT STD_LOGIC_VECTOR (751 downto 0);
        layer24_out_TVALID : OUT STD_LOGIC;
        layer24_out_TREADY : IN STD_LOGIC );
    end component;


    component myproject_fifo_w16_d784_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_fifo_w64_d676_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_fifo_w64_d169_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component myproject_fifo_w128_d121_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component myproject_fifo_w128_d25_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component myproject_fifo_w384_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (383 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (383 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component myproject_fifo_w752_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (751 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (751 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component myproject_start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config1tde IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config1udo IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23vdy IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20wdI IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24xdS IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0 : component myproject_transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_start,
        start_full_n => start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_full_n,
        ap_done => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_done,
        ap_continue => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_continue,
        ap_idle => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_idle,
        ap_ready => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_ready,
        start_out => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_start_out,
        start_write => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_start_write,
        global_in_TDATA => global_in_TDATA,
        global_in_TVALID => global_in_TVALID,
        global_in_TREADY => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_global_in_TREADY,
        layer10_out_din => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_din,
        layer10_out_full_n => layer10_out_full_n,
        layer10_out_write => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_write,
        layer10_out_num_data_valid => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_num_data_valid,
        layer10_out_fifo_cap => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_fifo_cap);

    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0 : component myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_full_n,
        ap_done => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_start_out,
        start_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_start_write,
        layer10_out_dout => layer10_out_dout,
        layer10_out_empty_n => layer10_out_empty_n,
        layer10_out_read => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer10_out_read,
        layer10_out_num_data_valid => layer10_out_num_data_valid,
        layer10_out_fifo_cap => layer10_out_fifo_cap,
        layer27_out_din => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer27_out_din,
        layer27_out_full_n => layer27_out_full_n,
        layer27_out_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer27_out_write,
        layer27_out_num_data_valid => layer27_out_num_data_valid,
        layer27_out_fifo_cap => layer27_out_fifo_cap);

    relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0 : component myproject_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_start,
        start_full_n => start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_full_n,
        ap_done => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_done,
        ap_continue => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_ready,
        start_out => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_start_out,
        start_write => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_start_write,
        layer27_out_dout => layer27_out_dout,
        layer27_out_empty_n => layer27_out_empty_n,
        layer27_out_read => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer27_out_read,
        layer27_out_num_data_valid => layer27_out_num_data_valid,
        layer27_out_fifo_cap => layer27_out_fifo_cap,
        layer12_out_din => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_din,
        layer12_out_full_n => layer12_out_full_n,
        layer12_out_write => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_write,
        layer12_out_num_data_valid => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_num_data_valid,
        layer12_out_fifo_cap => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_fifo_cap);

    pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0 : component myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_start,
        start_full_n => start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_full_n,
        ap_done => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_done,
        ap_continue => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_continue,
        ap_idle => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_idle,
        ap_ready => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_ready,
        start_out => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_start_out,
        start_write => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_start_write,
        layer12_out_dout => layer12_out_dout,
        layer12_out_empty_n => layer12_out_empty_n,
        layer12_out_read => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer12_out_read,
        layer12_out_num_data_valid => layer12_out_num_data_valid,
        layer12_out_fifo_cap => layer12_out_fifo_cap,
        layer13_out_din => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer13_out_din,
        layer13_out_full_n => layer13_out_full_n,
        layer13_out_write => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer13_out_write,
        layer13_out_num_data_valid => layer13_out_num_data_valid,
        layer13_out_fifo_cap => layer13_out_fifo_cap);

    conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0 : component myproject_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_full_n,
        ap_done => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_start_out,
        start_write => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_start_write,
        layer13_out_dout => layer13_out_dout,
        layer13_out_empty_n => layer13_out_empty_n,
        layer13_out_read => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer13_out_read,
        layer13_out_num_data_valid => layer13_out_num_data_valid,
        layer13_out_fifo_cap => layer13_out_fifo_cap,
        layer28_out_din => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer28_out_din,
        layer28_out_full_n => layer28_out_full_n,
        layer28_out_write => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer28_out_write,
        layer28_out_num_data_valid => layer28_out_num_data_valid,
        layer28_out_fifo_cap => layer28_out_fifo_cap);

    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0 : component myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_start,
        start_full_n => start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_full_n,
        ap_done => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_done,
        ap_continue => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_ready,
        layer28_out_dout => layer28_out_dout,
        layer28_out_empty_n => layer28_out_empty_n,
        layer28_out_read => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer28_out_read,
        layer28_out_num_data_valid => layer28_out_num_data_valid,
        layer28_out_fifo_cap => layer28_out_fifo_cap,
        layer15_out_din => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_din,
        layer15_out_full_n => layer15_out_full_n,
        layer15_out_write => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_write,
        layer15_out_num_data_valid => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_num_data_valid,
        layer15_out_fifo_cap => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_fifo_cap,
        start_out => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_start_out,
        start_write => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_start_write);

    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0 : component myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_full_n,
        ap_done => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_done,
        ap_continue => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_continue,
        ap_idle => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_idle,
        ap_ready => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_ready,
        start_out => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_start_out,
        start_write => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_start_write,
        layer15_out_dout => layer15_out_dout,
        layer15_out_empty_n => layer15_out_empty_n,
        layer15_out_read => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer15_out_read,
        layer15_out_num_data_valid => layer15_out_num_data_valid,
        layer15_out_fifo_cap => layer15_out_fifo_cap,
        layer16_out_din => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer16_out_din,
        layer16_out_full_n => layer16_out_full_n,
        layer16_out_write => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer16_out_write,
        layer16_out_num_data_valid => layer16_out_num_data_valid,
        layer16_out_fifo_cap => layer16_out_fifo_cap);

    dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0 : component myproject_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_start,
        start_full_n => start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_full_n,
        ap_done => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_done,
        ap_continue => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_ready,
        start_out => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_start_out,
        start_write => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_start_write,
        layer16_out_dout => layer16_out_dout,
        layer16_out_empty_n => layer16_out_empty_n,
        layer16_out_read => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer16_out_read,
        layer16_out_num_data_valid => layer16_out_num_data_valid,
        layer16_out_fifo_cap => layer16_out_fifo_cap,
        layer25_out_din => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer25_out_din,
        layer25_out_full_n => layer25_out_full_n,
        layer25_out_write => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer25_out_write,
        layer25_out_num_data_valid => layer25_out_num_data_valid,
        layer25_out_fifo_cap => layer25_out_fifo_cap);

    normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0 : component myproject_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_full_n,
        ap_done => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_done,
        ap_continue => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_continue,
        ap_idle => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_idle,
        ap_ready => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_ready,
        start_out => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_start_out,
        start_write => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_start_write,
        layer25_out_dout => layer25_out_dout,
        layer25_out_empty_n => layer25_out_empty_n,
        layer25_out_read => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer25_out_read,
        layer25_out_num_data_valid => layer25_out_num_data_valid,
        layer25_out_fifo_cap => layer25_out_fifo_cap,
        layer23_out_din => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer23_out_din,
        layer23_out_full_n => layer23_out_full_n,
        layer23_out_write => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer23_out_write,
        layer23_out_num_data_valid => layer23_out_num_data_valid,
        layer23_out_fifo_cap => layer23_out_fifo_cap);

    relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0 : component myproject_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_full_n,
        ap_done => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_done,
        ap_continue => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_ready,
        start_out => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_start_out,
        start_write => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_start_write,
        layer23_out_dout => layer23_out_dout,
        layer23_out_empty_n => layer23_out_empty_n,
        layer23_out_read => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer23_out_read,
        layer23_out_num_data_valid => layer23_out_num_data_valid,
        layer23_out_fifo_cap => layer23_out_fifo_cap,
        layer20_out_din => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer20_out_din,
        layer20_out_full_n => layer20_out_full_n,
        layer20_out_write => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer20_out_write,
        layer20_out_num_data_valid => layer20_out_num_data_valid,
        layer20_out_fifo_cap => layer20_out_fifo_cap);

    dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0 : component myproject_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_start,
        start_full_n => start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_full_n,
        ap_done => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_done,
        ap_continue => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_ready,
        start_out => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_start_out,
        start_write => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_start_write,
        layer20_out_dout => layer20_out_dout,
        layer20_out_empty_n => layer20_out_empty_n,
        layer20_out_read => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer20_out_read,
        layer20_out_num_data_valid => layer20_out_num_data_valid,
        layer20_out_fifo_cap => layer20_out_fifo_cap,
        layer26_out_din => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer26_out_din,
        layer26_out_full_n => layer26_out_full_n,
        layer26_out_write => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer26_out_write,
        layer26_out_num_data_valid => layer26_out_num_data_valid,
        layer26_out_fifo_cap => layer26_out_fifo_cap);

    normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0 : component myproject_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_start,
        ap_done => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_done,
        ap_continue => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_continue,
        ap_idle => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_idle,
        ap_ready => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_ready,
        layer26_out_dout => layer26_out_dout,
        layer26_out_empty_n => layer26_out_empty_n,
        layer26_out_read => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer26_out_read,
        layer26_out_num_data_valid => layer26_out_num_data_valid,
        layer26_out_fifo_cap => layer26_out_fifo_cap,
        layer24_out_TDATA => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer24_out_TDATA,
        layer24_out_TVALID => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer24_out_TVALID,
        layer24_out_TREADY => layer24_out_TREADY);

    layer10_out_U : component myproject_fifo_w16_d784_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_din,
        if_full_n => layer10_out_full_n,
        if_write => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_write,
        if_dout => layer10_out_dout,
        if_empty_n => layer10_out_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer10_out_read,
        if_num_data_valid => layer10_out_num_data_valid,
        if_fifo_cap => layer10_out_fifo_cap);

    layer27_out_U : component myproject_fifo_w64_d676_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer27_out_din,
        if_full_n => layer27_out_full_n,
        if_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_layer27_out_write,
        if_dout => layer27_out_dout,
        if_empty_n => layer27_out_empty_n,
        if_read => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer27_out_read,
        if_num_data_valid => layer27_out_num_data_valid,
        if_fifo_cap => layer27_out_fifo_cap);

    layer12_out_U : component myproject_fifo_w64_d676_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_din,
        if_full_n => layer12_out_full_n,
        if_write => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_write,
        if_dout => layer12_out_dout,
        if_empty_n => layer12_out_empty_n,
        if_read => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer12_out_read,
        if_num_data_valid => layer12_out_num_data_valid,
        if_fifo_cap => layer12_out_fifo_cap);

    layer13_out_U : component myproject_fifo_w64_d169_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer13_out_din,
        if_full_n => layer13_out_full_n,
        if_write => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_layer13_out_write,
        if_dout => layer13_out_dout,
        if_empty_n => layer13_out_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer13_out_read,
        if_num_data_valid => layer13_out_num_data_valid,
        if_fifo_cap => layer13_out_fifo_cap);

    layer28_out_U : component myproject_fifo_w128_d121_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer28_out_din,
        if_full_n => layer28_out_full_n,
        if_write => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_layer28_out_write,
        if_dout => layer28_out_dout,
        if_empty_n => layer28_out_empty_n,
        if_read => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer28_out_read,
        if_num_data_valid => layer28_out_num_data_valid,
        if_fifo_cap => layer28_out_fifo_cap);

    layer15_out_U : component myproject_fifo_w128_d121_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_din,
        if_full_n => layer15_out_full_n,
        if_write => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_write,
        if_dout => layer15_out_dout,
        if_empty_n => layer15_out_empty_n,
        if_read => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer15_out_read,
        if_num_data_valid => layer15_out_num_data_valid,
        if_fifo_cap => layer15_out_fifo_cap);

    layer16_out_U : component myproject_fifo_w128_d25_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer16_out_din,
        if_full_n => layer16_out_full_n,
        if_write => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_layer16_out_write,
        if_dout => layer16_out_dout,
        if_empty_n => layer16_out_empty_n,
        if_read => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer16_out_read,
        if_num_data_valid => layer16_out_num_data_valid,
        if_fifo_cap => layer16_out_fifo_cap);

    layer25_out_U : component myproject_fifo_w384_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer25_out_din,
        if_full_n => layer25_out_full_n,
        if_write => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_layer25_out_write,
        if_dout => layer25_out_dout,
        if_empty_n => layer25_out_empty_n,
        if_read => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer25_out_read,
        if_num_data_valid => layer25_out_num_data_valid,
        if_fifo_cap => layer25_out_fifo_cap);

    layer23_out_U : component myproject_fifo_w384_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer23_out_din,
        if_full_n => layer23_out_full_n,
        if_write => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_layer23_out_write,
        if_dout => layer23_out_dout,
        if_empty_n => layer23_out_empty_n,
        if_read => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer23_out_read,
        if_num_data_valid => layer23_out_num_data_valid,
        if_fifo_cap => layer23_out_fifo_cap);

    layer20_out_U : component myproject_fifo_w384_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer20_out_din,
        if_full_n => layer20_out_full_n,
        if_write => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_layer20_out_write,
        if_dout => layer20_out_dout,
        if_empty_n => layer20_out_empty_n,
        if_read => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer20_out_read,
        if_num_data_valid => layer20_out_num_data_valid,
        if_fifo_cap => layer20_out_fifo_cap);

    layer26_out_U : component myproject_fifo_w752_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer26_out_din,
        if_full_n => layer26_out_full_n,
        if_write => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_layer26_out_write,
        if_dout => layer26_out_dout,
        if_empty_n => layer26_out_empty_n,
        if_read => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer26_out_read,
        if_num_data_valid => layer26_out_num_data_valid,
        if_fifo_cap => layer26_out_fifo_cap);

    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_U : component myproject_start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_din,
        if_full_n => start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_full_n,
        if_write => transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_start_write,
        if_dout => start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_dout,
        if_empty_n => start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_ready);

    start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_U : component myproject_start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_full_n,
        if_write => conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_empty_n,
        if_read => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_ready);

    start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config1tde_U : component myproject_start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config1tde
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_din,
        if_full_n => start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_full_n,
        if_write => relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_start_write,
        if_dout => start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_dout,
        if_empty_n => start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_empty_n,
        if_read => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_ready);

    start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_U : component myproject_start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_din,
        if_full_n => start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_full_n,
        if_write => pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_start_write,
        if_dout => start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_dout,
        if_empty_n => start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_empty_n,
        if_read => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_ready);

    start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_U : component myproject_start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_full_n,
        if_write => conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_empty_n,
        if_read => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_ready);

    start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config1udo_U : component myproject_start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config1udo
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_din,
        if_full_n => start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_full_n,
        if_write => relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_start_write,
        if_dout => start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_dout,
        if_empty_n => start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_empty_n,
        if_read => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_ready);

    start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_U : component myproject_start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_full_n,
        if_write => pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_empty_n,
        if_read => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_ready);

    start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23vdy_U : component myproject_start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23vdy
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_din,
        if_full_n => start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_full_n,
        if_write => dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_start_write,
        if_dout => start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_dout,
        if_empty_n => start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_empty_n,
        if_read => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_ready);

    start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20wdI_U : component myproject_start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20wdI
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_full_n,
        if_write => normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_empty_n,
        if_read => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_ready);

    start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_U : component myproject_start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_full_n,
        if_write => relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_empty_n,
        if_read => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_ready);

    start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24xdS_U : component myproject_start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24xdS
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_din,
        if_full_n => start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_full_n,
        if_write => dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_start_write,
        if_dout => start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_dout,
        if_empty_n => start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_empty_n,
        if_read => normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_ready);




    ap_done <= normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_done;
    ap_idle <= (transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_idle and relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_idle and relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_idle and relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_idle and pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_idle and pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_idle and normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_idle and normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_idle and dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_idle and dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_idle and conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_idle and conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_idle);
    ap_ready <= transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_ap_start <= start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_empty_n;
    conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_ap_start <= start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_empty_n;
    dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_ap_start <= start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_empty_n;
    dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_ap_start <= start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_empty_n;
    global_in_TREADY <= transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_global_in_TREADY;
    layer24_out_TDATA <= normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer24_out_TDATA;
    layer24_out_TVALID <= normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_layer24_out_TVALID;
    normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_continue <= ap_const_logic_1;
    normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_ap_start <= start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_empty_n;
    normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_continue <= ap_const_logic_1;
    normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_ap_start <= start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_empty_n;
    pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_continue <= ap_const_logic_1;
    pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_ap_start <= start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_empty_n;
    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_continue <= ap_const_logic_1;
    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_ap_start <= start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_empty_n;
    relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_ap_start <= start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_empty_n;
    relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_ap_start <= start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_empty_n;
    relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer12_out_fifo_cap),11))),32));
    relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_layer12_out_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer12_out_num_data_valid),11))),32));
    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_ap_start <= start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_empty_n;
    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer15_out_fifo_cap),8))),32));
    relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_layer15_out_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer15_out_num_data_valid),8))),32));
    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_4u_config27_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config28_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_47u_config26_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_24u_config25_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_normalize_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_config23_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config13_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config16_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_24u_ReLU_config20_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_ReLU_config12_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_U0_din <= (0=>ap_const_logic_1, others=>'-');
    transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_continue <= ap_const_logic_1;
    transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_ap_start <= ap_start;
    transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer10_out_fifo_cap),11))),32));
    transpose_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_1u_config10_U0_layer10_out_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer10_out_num_data_valid),11))),32));
end behav;
