-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer26_out_dout : IN STD_LOGIC_VECTOR (751 downto 0);
    layer26_out_empty_n : IN STD_LOGIC;
    layer26_out_read : OUT STD_LOGIC;
    layer26_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer26_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer24_out_TDATA : OUT STD_LOGIC_VECTOR (751 downto 0);
    layer24_out_TVALID : OUT STD_LOGIC;
    layer24_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_normalize_array_ap_fixed_47u_array_ap_fixed_16_6_5_3_0_47u_config24_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv32_20F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000001111";
    constant ap_const_lv32_210 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000010000";
    constant ap_const_lv32_21F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000011111";
    constant ap_const_lv32_220 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000100000";
    constant ap_const_lv32_22F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000101111";
    constant ap_const_lv32_230 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000110000";
    constant ap_const_lv32_23F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111111";
    constant ap_const_lv32_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000000";
    constant ap_const_lv32_24F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001001111";
    constant ap_const_lv32_250 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001010000";
    constant ap_const_lv32_25F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001011111";
    constant ap_const_lv32_260 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001100000";
    constant ap_const_lv32_26F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001101111";
    constant ap_const_lv32_270 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001110000";
    constant ap_const_lv32_27F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001111111";
    constant ap_const_lv32_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000000";
    constant ap_const_lv32_28F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010001111";
    constant ap_const_lv32_290 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010010000";
    constant ap_const_lv32_29F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010011111";
    constant ap_const_lv32_2A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010100000";
    constant ap_const_lv32_2AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010101111";
    constant ap_const_lv32_2B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010110000";
    constant ap_const_lv32_2BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010111111";
    constant ap_const_lv32_2C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011000000";
    constant ap_const_lv32_2CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011001111";
    constant ap_const_lv32_2D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011010000";
    constant ap_const_lv32_2DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011011111";
    constant ap_const_lv32_2E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011100000";
    constant ap_const_lv32_2EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011101111";
    constant ap_const_lv16_FE1F : STD_LOGIC_VECTOR (15 downto 0) := "1111111000011111";
    constant ap_const_lv16_FFEB : STD_LOGIC_VECTOR (15 downto 0) := "1111111111101011";
    constant ap_const_lv16_E1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011100001";
    constant ap_const_lv16_45 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000101";
    constant ap_const_lv16_FFBD : STD_LOGIC_VECTOR (15 downto 0) := "1111111110111101";
    constant ap_const_lv16_FE91 : STD_LOGIC_VECTOR (15 downto 0) := "1111111010010001";
    constant ap_const_lv16_F0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011110000";
    constant ap_const_lv16_FF7C : STD_LOGIC_VECTOR (15 downto 0) := "1111111101111100";
    constant ap_const_lv16_EE : STD_LOGIC_VECTOR (15 downto 0) := "0000000011101110";
    constant ap_const_lv16_FF85 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000101";
    constant ap_const_lv16_FFCB : STD_LOGIC_VECTOR (15 downto 0) := "1111111111001011";
    constant ap_const_lv16_FF18 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100011000";
    constant ap_const_lv16_FFDC : STD_LOGIC_VECTOR (15 downto 0) := "1111111111011100";
    constant ap_const_lv16_FF81 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000001";
    constant ap_const_lv16_FFF9 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111001";
    constant ap_const_lv16_FD19 : STD_LOGIC_VECTOR (15 downto 0) := "1111110100011001";
    constant ap_const_lv16_FD88 : STD_LOGIC_VECTOR (15 downto 0) := "1111110110001000";
    constant ap_const_lv16_2A4 : STD_LOGIC_VECTOR (15 downto 0) := "0000001010100100";
    constant ap_const_lv16_FF82 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000010";
    constant ap_const_lv16_FE65 : STD_LOGIC_VECTOR (15 downto 0) := "1111111001100101";
    constant ap_const_lv16_11C : STD_LOGIC_VECTOR (15 downto 0) := "0000000100011100";
    constant ap_const_lv16_FE7C : STD_LOGIC_VECTOR (15 downto 0) := "1111111001111100";
    constant ap_const_lv16_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000111";
    constant ap_const_lv16_D3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011010011";
    constant ap_const_lv16_1B8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000110111000";
    constant ap_const_lv16_FC83 : STD_LOGIC_VECTOR (15 downto 0) := "1111110010000011";
    constant ap_const_lv16_14C : STD_LOGIC_VECTOR (15 downto 0) := "0000000101001100";
    constant ap_const_lv16_125 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100100101";
    constant ap_const_lv16_FEBC : STD_LOGIC_VECTOR (15 downto 0) := "1111111010111100";
    constant ap_const_lv16_FFA9 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110101001";
    constant ap_const_lv16_FDBF : STD_LOGIC_VECTOR (15 downto 0) := "1111110110111111";
    constant ap_const_lv16_FFEA : STD_LOGIC_VECTOR (15 downto 0) := "1111111111101010";
    constant ap_const_lv16_FF69 : STD_LOGIC_VECTOR (15 downto 0) := "1111111101101001";
    constant ap_const_lv16_FF0F : STD_LOGIC_VECTOR (15 downto 0) := "1111111100001111";
    constant ap_const_lv16_17A : STD_LOGIC_VECTOR (15 downto 0) := "0000000101111010";
    constant ap_const_lv16_C0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011000000";
    constant ap_const_lv16_FFA7 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110100111";
    constant ap_const_lv16_1C4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000111000100";
    constant ap_const_lv16_FFA2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110100010";
    constant ap_const_lv16_FFC3 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111000011";
    constant ap_const_lv16_93 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010011";
    constant ap_const_lv16_1A3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000110100011";
    constant ap_const_lv16_D7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011010111";
    constant ap_const_lv16_FCCC : STD_LOGIC_VECTOR (15 downto 0) := "1111110011001100";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer26_out_blk_n : STD_LOGIC;
    signal layer24_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln28_fu_319_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_reg_1070 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln28_1_reg_1075 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_2_reg_1080 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_3_reg_1085 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_4_reg_1090 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_5_reg_1095 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_6_reg_1100 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_7_reg_1105 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_8_reg_1110 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_9_reg_1115 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_s_reg_1120 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_10_reg_1125 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_11_reg_1130 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_12_reg_1135 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_13_reg_1140 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_14_reg_1145 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_15_reg_1150 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_16_reg_1155 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_17_reg_1160 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_18_reg_1165 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_19_reg_1170 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_20_reg_1175 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_21_reg_1180 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_22_reg_1185 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_23_reg_1190 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_24_reg_1195 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_25_reg_1200 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_26_reg_1205 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_27_reg_1210 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_28_reg_1215 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_29_reg_1220 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_30_reg_1225 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_31_reg_1230 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_32_reg_1235 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_33_reg_1240 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_34_reg_1245 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_35_reg_1250 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_36_reg_1255 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_37_reg_1260 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_38_reg_1265 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_39_reg_1270 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_40_reg_1275 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_41_reg_1280 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_42_reg_1285 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_43_reg_1290 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_44_reg_1295 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_45_reg_1300 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_fu_783_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_reg_1305 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln42_1_fu_788_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_1_reg_1310 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_2_fu_793_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_2_reg_1315 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_3_fu_798_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_3_reg_1320 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_4_fu_803_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_4_reg_1325 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_5_fu_808_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_5_reg_1330 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_6_fu_813_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_6_reg_1335 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_7_fu_818_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_7_reg_1340 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_8_fu_823_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_8_reg_1345 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_9_fu_828_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_9_reg_1350 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_10_fu_833_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_10_reg_1355 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_11_fu_838_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_11_reg_1360 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_12_fu_843_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_12_reg_1365 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_13_fu_848_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_13_reg_1370 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_14_fu_853_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_14_reg_1375 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_15_fu_858_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_15_reg_1380 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_16_fu_863_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_16_reg_1385 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_17_fu_868_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_17_reg_1390 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_18_fu_873_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_18_reg_1395 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_19_fu_878_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_19_reg_1400 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_20_fu_883_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_20_reg_1405 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_21_fu_888_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_21_reg_1410 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_22_fu_893_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_22_reg_1415 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_23_fu_898_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_23_reg_1420 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_24_fu_903_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_24_reg_1425 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_25_fu_908_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_25_reg_1430 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_26_fu_913_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_26_reg_1435 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_27_fu_918_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_27_reg_1440 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_28_fu_923_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_28_reg_1445 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_29_fu_928_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_29_reg_1450 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_30_fu_933_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_30_reg_1455 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_31_fu_938_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_31_reg_1460 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_32_fu_943_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_32_reg_1465 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_33_fu_948_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_33_reg_1470 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_34_fu_953_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_34_reg_1475 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_35_fu_958_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_35_reg_1480 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_36_fu_963_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_36_reg_1485 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_37_fu_968_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_37_reg_1490 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_38_fu_973_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_38_reg_1495 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_39_fu_978_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_39_reg_1500 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_40_fu_983_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_40_reg_1505 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_41_fu_988_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_41_reg_1510 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_42_fu_993_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_42_reg_1515 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_43_fu_998_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_43_reg_1520 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_44_fu_1003_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_44_reg_1525 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_45_fu_1008_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_45_reg_1530 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_46_fu_1013_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln42_46_reg_1535 : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_layer24_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state4 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal layer24_out_TDATA_int_regslice : STD_LOGIC_VECTOR (751 downto 0);
    signal layer24_out_TVALID_int_regslice : STD_LOGIC;
    signal layer24_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_layer24_out_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_layer24_out_U : component myproject_regslice_both
    generic map (
        DataWidth => 752)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => layer24_out_TDATA_int_regslice,
        vld_in => layer24_out_TVALID_int_regslice,
        ack_in => layer24_out_TREADY_int_regslice,
        data_out => layer24_out_TDATA,
        vld_out => regslice_both_layer24_out_U_vld_out,
        ack_out => layer24_out_TREADY,
        apdone_blk => regslice_both_layer24_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln42_10_reg_1355 <= add_ln42_10_fu_833_p2;
                add_ln42_11_reg_1360 <= add_ln42_11_fu_838_p2;
                add_ln42_12_reg_1365 <= add_ln42_12_fu_843_p2;
                add_ln42_13_reg_1370 <= add_ln42_13_fu_848_p2;
                add_ln42_14_reg_1375 <= add_ln42_14_fu_853_p2;
                add_ln42_15_reg_1380 <= add_ln42_15_fu_858_p2;
                add_ln42_16_reg_1385 <= add_ln42_16_fu_863_p2;
                add_ln42_17_reg_1390 <= add_ln42_17_fu_868_p2;
                add_ln42_18_reg_1395 <= add_ln42_18_fu_873_p2;
                add_ln42_19_reg_1400 <= add_ln42_19_fu_878_p2;
                add_ln42_1_reg_1310 <= add_ln42_1_fu_788_p2;
                add_ln42_20_reg_1405 <= add_ln42_20_fu_883_p2;
                add_ln42_21_reg_1410 <= add_ln42_21_fu_888_p2;
                add_ln42_22_reg_1415 <= add_ln42_22_fu_893_p2;
                add_ln42_23_reg_1420 <= add_ln42_23_fu_898_p2;
                add_ln42_24_reg_1425 <= add_ln42_24_fu_903_p2;
                add_ln42_25_reg_1430 <= add_ln42_25_fu_908_p2;
                add_ln42_26_reg_1435 <= add_ln42_26_fu_913_p2;
                add_ln42_27_reg_1440 <= add_ln42_27_fu_918_p2;
                add_ln42_28_reg_1445 <= add_ln42_28_fu_923_p2;
                add_ln42_29_reg_1450 <= add_ln42_29_fu_928_p2;
                add_ln42_2_reg_1315 <= add_ln42_2_fu_793_p2;
                add_ln42_30_reg_1455 <= add_ln42_30_fu_933_p2;
                add_ln42_31_reg_1460 <= add_ln42_31_fu_938_p2;
                add_ln42_32_reg_1465 <= add_ln42_32_fu_943_p2;
                add_ln42_33_reg_1470 <= add_ln42_33_fu_948_p2;
                add_ln42_34_reg_1475 <= add_ln42_34_fu_953_p2;
                add_ln42_35_reg_1480 <= add_ln42_35_fu_958_p2;
                add_ln42_36_reg_1485 <= add_ln42_36_fu_963_p2;
                add_ln42_37_reg_1490 <= add_ln42_37_fu_968_p2;
                add_ln42_38_reg_1495 <= add_ln42_38_fu_973_p2;
                add_ln42_39_reg_1500 <= add_ln42_39_fu_978_p2;
                add_ln42_3_reg_1320 <= add_ln42_3_fu_798_p2;
                add_ln42_40_reg_1505 <= add_ln42_40_fu_983_p2;
                add_ln42_41_reg_1510 <= add_ln42_41_fu_988_p2;
                add_ln42_42_reg_1515 <= add_ln42_42_fu_993_p2;
                add_ln42_43_reg_1520 <= add_ln42_43_fu_998_p2;
                add_ln42_44_reg_1525 <= add_ln42_44_fu_1003_p2;
                add_ln42_45_reg_1530 <= add_ln42_45_fu_1008_p2;
                add_ln42_46_reg_1535 <= add_ln42_46_fu_1013_p2;
                add_ln42_4_reg_1325 <= add_ln42_4_fu_803_p2;
                add_ln42_5_reg_1330 <= add_ln42_5_fu_808_p2;
                add_ln42_6_reg_1335 <= add_ln42_6_fu_813_p2;
                add_ln42_7_reg_1340 <= add_ln42_7_fu_818_p2;
                add_ln42_8_reg_1345 <= add_ln42_8_fu_823_p2;
                add_ln42_9_reg_1350 <= add_ln42_9_fu_828_p2;
                add_ln42_reg_1305 <= add_ln42_fu_783_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_ln28_10_reg_1125 <= layer26_out_dout(191 downto 176);
                trunc_ln28_11_reg_1130 <= layer26_out_dout(207 downto 192);
                trunc_ln28_12_reg_1135 <= layer26_out_dout(223 downto 208);
                trunc_ln28_13_reg_1140 <= layer26_out_dout(239 downto 224);
                trunc_ln28_14_reg_1145 <= layer26_out_dout(255 downto 240);
                trunc_ln28_15_reg_1150 <= layer26_out_dout(271 downto 256);
                trunc_ln28_16_reg_1155 <= layer26_out_dout(287 downto 272);
                trunc_ln28_17_reg_1160 <= layer26_out_dout(303 downto 288);
                trunc_ln28_18_reg_1165 <= layer26_out_dout(319 downto 304);
                trunc_ln28_19_reg_1170 <= layer26_out_dout(335 downto 320);
                trunc_ln28_1_reg_1075 <= layer26_out_dout(31 downto 16);
                trunc_ln28_20_reg_1175 <= layer26_out_dout(351 downto 336);
                trunc_ln28_21_reg_1180 <= layer26_out_dout(367 downto 352);
                trunc_ln28_22_reg_1185 <= layer26_out_dout(383 downto 368);
                trunc_ln28_23_reg_1190 <= layer26_out_dout(399 downto 384);
                trunc_ln28_24_reg_1195 <= layer26_out_dout(415 downto 400);
                trunc_ln28_25_reg_1200 <= layer26_out_dout(431 downto 416);
                trunc_ln28_26_reg_1205 <= layer26_out_dout(447 downto 432);
                trunc_ln28_27_reg_1210 <= layer26_out_dout(463 downto 448);
                trunc_ln28_28_reg_1215 <= layer26_out_dout(479 downto 464);
                trunc_ln28_29_reg_1220 <= layer26_out_dout(495 downto 480);
                trunc_ln28_2_reg_1080 <= layer26_out_dout(47 downto 32);
                trunc_ln28_30_reg_1225 <= layer26_out_dout(511 downto 496);
                trunc_ln28_31_reg_1230 <= layer26_out_dout(527 downto 512);
                trunc_ln28_32_reg_1235 <= layer26_out_dout(543 downto 528);
                trunc_ln28_33_reg_1240 <= layer26_out_dout(559 downto 544);
                trunc_ln28_34_reg_1245 <= layer26_out_dout(575 downto 560);
                trunc_ln28_35_reg_1250 <= layer26_out_dout(591 downto 576);
                trunc_ln28_36_reg_1255 <= layer26_out_dout(607 downto 592);
                trunc_ln28_37_reg_1260 <= layer26_out_dout(623 downto 608);
                trunc_ln28_38_reg_1265 <= layer26_out_dout(639 downto 624);
                trunc_ln28_39_reg_1270 <= layer26_out_dout(655 downto 640);
                trunc_ln28_3_reg_1085 <= layer26_out_dout(63 downto 48);
                trunc_ln28_40_reg_1275 <= layer26_out_dout(671 downto 656);
                trunc_ln28_41_reg_1280 <= layer26_out_dout(687 downto 672);
                trunc_ln28_42_reg_1285 <= layer26_out_dout(703 downto 688);
                trunc_ln28_43_reg_1290 <= layer26_out_dout(719 downto 704);
                trunc_ln28_44_reg_1295 <= layer26_out_dout(735 downto 720);
                trunc_ln28_45_reg_1300 <= layer26_out_dout(751 downto 736);
                trunc_ln28_4_reg_1090 <= layer26_out_dout(79 downto 64);
                trunc_ln28_5_reg_1095 <= layer26_out_dout(95 downto 80);
                trunc_ln28_6_reg_1100 <= layer26_out_dout(111 downto 96);
                trunc_ln28_7_reg_1105 <= layer26_out_dout(127 downto 112);
                trunc_ln28_8_reg_1110 <= layer26_out_dout(143 downto 128);
                trunc_ln28_9_reg_1115 <= layer26_out_dout(159 downto 144);
                trunc_ln28_reg_1070 <= trunc_ln28_fu_319_p1;
                trunc_ln28_s_reg_1120 <= layer26_out_dout(175 downto 160);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state1, ap_block_state4, layer24_out_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((layer24_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln42_10_fu_833_p2 <= std_logic_vector(unsigned(trunc_ln28_s_reg_1120) + unsigned(ap_const_lv16_FFCB));
    add_ln42_11_fu_838_p2 <= std_logic_vector(unsigned(trunc_ln28_10_reg_1125) + unsigned(ap_const_lv16_FF18));
    add_ln42_12_fu_843_p2 <= std_logic_vector(unsigned(trunc_ln28_11_reg_1130) + unsigned(ap_const_lv16_FFDC));
    add_ln42_13_fu_848_p2 <= std_logic_vector(unsigned(trunc_ln28_12_reg_1135) + unsigned(ap_const_lv16_FF81));
    add_ln42_14_fu_853_p2 <= std_logic_vector(unsigned(trunc_ln28_13_reg_1140) + unsigned(ap_const_lv16_E1));
    add_ln42_15_fu_858_p2 <= std_logic_vector(unsigned(trunc_ln28_14_reg_1145) + unsigned(ap_const_lv16_FFF9));
    add_ln42_16_fu_863_p2 <= std_logic_vector(unsigned(trunc_ln28_15_reg_1150) + unsigned(ap_const_lv16_FD19));
    add_ln42_17_fu_868_p2 <= std_logic_vector(unsigned(trunc_ln28_16_reg_1155) + unsigned(ap_const_lv16_FD88));
    add_ln42_18_fu_873_p2 <= std_logic_vector(unsigned(trunc_ln28_17_reg_1160) + unsigned(ap_const_lv16_2A4));
    add_ln42_19_fu_878_p2 <= std_logic_vector(unsigned(trunc_ln28_18_reg_1165) + unsigned(ap_const_lv16_FF82));
    add_ln42_1_fu_788_p2 <= std_logic_vector(unsigned(trunc_ln28_1_reg_1075) + unsigned(ap_const_lv16_FFEB));
    add_ln42_20_fu_883_p2 <= std_logic_vector(unsigned(trunc_ln28_19_reg_1170) + unsigned(ap_const_lv16_FE65));
    add_ln42_21_fu_888_p2 <= std_logic_vector(unsigned(trunc_ln28_20_reg_1175) + unsigned(ap_const_lv16_11C));
    add_ln42_22_fu_893_p2 <= std_logic_vector(unsigned(trunc_ln28_21_reg_1180) + unsigned(ap_const_lv16_FE7C));
    add_ln42_23_fu_898_p2 <= std_logic_vector(unsigned(trunc_ln28_22_reg_1185) + unsigned(ap_const_lv16_7));
    add_ln42_24_fu_903_p2 <= std_logic_vector(unsigned(trunc_ln28_23_reg_1190) + unsigned(ap_const_lv16_D3));
    add_ln42_25_fu_908_p2 <= std_logic_vector(unsigned(trunc_ln28_24_reg_1195) + unsigned(ap_const_lv16_1B8));
    add_ln42_26_fu_913_p2 <= std_logic_vector(unsigned(trunc_ln28_25_reg_1200) + unsigned(ap_const_lv16_FC83));
    add_ln42_27_fu_918_p2 <= std_logic_vector(unsigned(trunc_ln28_26_reg_1205) + unsigned(ap_const_lv16_14C));
    add_ln42_28_fu_923_p2 <= std_logic_vector(unsigned(trunc_ln28_27_reg_1210) + unsigned(ap_const_lv16_125));
    add_ln42_29_fu_928_p2 <= std_logic_vector(unsigned(trunc_ln28_28_reg_1215) + unsigned(ap_const_lv16_FEBC));
    add_ln42_2_fu_793_p2 <= std_logic_vector(unsigned(trunc_ln28_2_reg_1080) + unsigned(ap_const_lv16_E1));
    add_ln42_30_fu_933_p2 <= std_logic_vector(unsigned(trunc_ln28_29_reg_1220) + unsigned(ap_const_lv16_FFA9));
    add_ln42_31_fu_938_p2 <= std_logic_vector(unsigned(trunc_ln28_30_reg_1225) + unsigned(ap_const_lv16_1B8));
    add_ln42_32_fu_943_p2 <= std_logic_vector(unsigned(trunc_ln28_31_reg_1230) + unsigned(ap_const_lv16_FDBF));
    add_ln42_33_fu_948_p2 <= std_logic_vector(unsigned(trunc_ln28_32_reg_1235) + unsigned(ap_const_lv16_FFEA));
    add_ln42_34_fu_953_p2 <= std_logic_vector(unsigned(trunc_ln28_33_reg_1240) + unsigned(ap_const_lv16_FF69));
    add_ln42_35_fu_958_p2 <= std_logic_vector(unsigned(trunc_ln28_34_reg_1245) + unsigned(ap_const_lv16_FF0F));
    add_ln42_36_fu_963_p2 <= std_logic_vector(unsigned(trunc_ln28_35_reg_1250) + unsigned(ap_const_lv16_17A));
    add_ln42_37_fu_968_p2 <= std_logic_vector(unsigned(trunc_ln28_36_reg_1255) + unsigned(ap_const_lv16_C0));
    add_ln42_38_fu_973_p2 <= std_logic_vector(unsigned(trunc_ln28_37_reg_1260) + unsigned(ap_const_lv16_FFA7));
    add_ln42_39_fu_978_p2 <= std_logic_vector(unsigned(trunc_ln28_38_reg_1265) + unsigned(ap_const_lv16_1C4));
    add_ln42_3_fu_798_p2 <= std_logic_vector(unsigned(trunc_ln28_3_reg_1085) + unsigned(ap_const_lv16_45));
    add_ln42_40_fu_983_p2 <= std_logic_vector(unsigned(trunc_ln28_39_reg_1270) + unsigned(ap_const_lv16_FFA2));
    add_ln42_41_fu_988_p2 <= std_logic_vector(unsigned(trunc_ln28_40_reg_1275) + unsigned(ap_const_lv16_FFC3));
    add_ln42_42_fu_993_p2 <= std_logic_vector(unsigned(trunc_ln28_41_reg_1280) + unsigned(ap_const_lv16_93));
    add_ln42_43_fu_998_p2 <= std_logic_vector(unsigned(trunc_ln28_42_reg_1285) + unsigned(ap_const_lv16_11C));
    add_ln42_44_fu_1003_p2 <= std_logic_vector(unsigned(trunc_ln28_43_reg_1290) + unsigned(ap_const_lv16_1A3));
    add_ln42_45_fu_1008_p2 <= std_logic_vector(unsigned(trunc_ln28_44_reg_1295) + unsigned(ap_const_lv16_D7));
    add_ln42_46_fu_1013_p2 <= std_logic_vector(unsigned(trunc_ln28_45_reg_1300) + unsigned(ap_const_lv16_FCCC));
    add_ln42_4_fu_803_p2 <= std_logic_vector(unsigned(trunc_ln28_4_reg_1090) + unsigned(ap_const_lv16_FFBD));
    add_ln42_5_fu_808_p2 <= std_logic_vector(unsigned(trunc_ln28_5_reg_1095) + unsigned(ap_const_lv16_FE91));
    add_ln42_6_fu_813_p2 <= std_logic_vector(unsigned(trunc_ln28_6_reg_1100) + unsigned(ap_const_lv16_F0));
    add_ln42_7_fu_818_p2 <= std_logic_vector(unsigned(trunc_ln28_7_reg_1105) + unsigned(ap_const_lv16_FF7C));
    add_ln42_8_fu_823_p2 <= std_logic_vector(unsigned(trunc_ln28_8_reg_1110) + unsigned(ap_const_lv16_EE));
    add_ln42_9_fu_828_p2 <= std_logic_vector(unsigned(trunc_ln28_9_reg_1115) + unsigned(ap_const_lv16_FF85));
    add_ln42_fu_783_p2 <= std_logic_vector(unsigned(trunc_ln28_reg_1070) + unsigned(ap_const_lv16_FE1F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer24_out_TREADY_int_regslice)
    begin
        if ((layer24_out_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, layer26_out_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (layer26_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state4_assign_proc : process(regslice_both_layer24_out_U_apdone_blk, layer24_out_TREADY_int_regslice)
    begin
                ap_block_state4 <= ((layer24_out_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_layer24_out_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer24_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, layer24_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer24_out_TDATA_blk_n <= layer24_out_TREADY_int_regslice;
        else 
            layer24_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer24_out_TDATA_int_regslice <= ((((((((((((((((((((((((((((((((((((((((((((((add_ln42_46_reg_1535 & add_ln42_45_reg_1530) & add_ln42_44_reg_1525) & add_ln42_43_reg_1520) & add_ln42_42_reg_1515) & add_ln42_41_reg_1510) & add_ln42_40_reg_1505) & add_ln42_39_reg_1500) & add_ln42_38_reg_1495) & add_ln42_37_reg_1490) & add_ln42_36_reg_1485) & add_ln42_35_reg_1480) & add_ln42_34_reg_1475) & add_ln42_33_reg_1470) & add_ln42_32_reg_1465) & add_ln42_31_reg_1460) & add_ln42_30_reg_1455) & add_ln42_29_reg_1450) & add_ln42_28_reg_1445) & add_ln42_27_reg_1440) & add_ln42_26_reg_1435) & add_ln42_25_reg_1430) & add_ln42_24_reg_1425) & add_ln42_23_reg_1420) & add_ln42_22_reg_1415) & add_ln42_21_reg_1410) & add_ln42_20_reg_1405) & add_ln42_19_reg_1400) & add_ln42_18_reg_1395) & add_ln42_17_reg_1390) & add_ln42_16_reg_1385) & add_ln42_15_reg_1380) & add_ln42_14_reg_1375) & add_ln42_13_reg_1370) & add_ln42_12_reg_1365) & add_ln42_11_reg_1360) & add_ln42_10_reg_1355) & add_ln42_9_reg_1350) & add_ln42_8_reg_1345) & add_ln42_7_reg_1340) & add_ln42_6_reg_1335) & 
    add_ln42_5_reg_1330) & add_ln42_4_reg_1325) & add_ln42_3_reg_1320) & add_ln42_2_reg_1315) & add_ln42_1_reg_1310) & add_ln42_reg_1305);
    layer24_out_TVALID <= regslice_both_layer24_out_U_vld_out;

    layer24_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state3, layer24_out_TREADY_int_regslice)
    begin
        if (((layer24_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer24_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            layer24_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    layer26_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer26_out_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer26_out_blk_n <= layer26_out_empty_n;
        else 
            layer26_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer26_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer26_out_read <= ap_const_logic_1;
        else 
            layer26_out_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln28_fu_319_p1 <= layer26_out_dout(16 - 1 downto 0);
end behav;
