-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer28_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    layer28_out_empty_n : IN STD_LOGIC;
    layer28_out_read : OUT STD_LOGIC;
    layer28_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer28_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer15_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    layer15_out_full_n : IN STD_LOGIC;
    layer15_out_write : OUT STD_LOGIC;
    layer15_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    layer15_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_ReLU_config15_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_5E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011110";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_78 : STD_LOGIC_VECTOR (6 downto 0) := "1111000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer28_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal layer15_out_blk_n : STD_LOGIC;
    signal trunc_ln44_fu_113_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_reg_426 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal trunc_ln44_14_fu_117_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_14_reg_431 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_1_reg_436 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_8_reg_441 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_2_reg_446 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_9_reg_451 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_3_reg_456 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_s_reg_461 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_4_reg_466 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_10_reg_471 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_5_reg_476 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_11_reg_481 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_6_reg_486 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_12_reg_491 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln44_7_reg_496 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_reg_501 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln51_fu_283_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_reg_510 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_1_fu_295_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_1_reg_515 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_2_fu_307_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_2_reg_520 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_3_fu_319_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_3_reg_525 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_4_fu_331_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_4_reg_530 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_5_fu_343_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_5_reg_535 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_6_fu_355_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_6_reg_540 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_7_fu_367_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln51_7_reg_545 : STD_LOGIC_VECTOR (14 downto 0);
    signal i_fu_88 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_5_fu_261_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal icmp_ln51_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_1_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_2_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_3_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_4_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_5_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_6_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_7_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln51_6_fu_392_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_5_fu_389_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_4_fu_386_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_3_fu_383_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_2_fu_380_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_1_fu_377_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_fu_374_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln57_s_fu_395_p9 : STD_LOGIC_VECTOR (126 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_88 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_88 <= i_5_fu_261_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                select_ln51_1_reg_515 <= select_ln51_1_fu_295_p3;
                select_ln51_2_reg_520 <= select_ln51_2_fu_307_p3;
                select_ln51_3_reg_525 <= select_ln51_3_fu_319_p3;
                select_ln51_4_reg_530 <= select_ln51_4_fu_331_p3;
                select_ln51_5_reg_535 <= select_ln51_5_fu_343_p3;
                select_ln51_6_reg_540 <= select_ln51_6_fu_355_p3;
                select_ln51_7_reg_545 <= select_ln51_7_fu_367_p3;
                select_ln51_reg_510 <= select_ln51_fu_283_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln1_reg_501 <= layer28_out_dout(126 downto 112);
                trunc_ln44_10_reg_471 <= layer28_out_dout(78 downto 64);
                trunc_ln44_11_reg_481 <= layer28_out_dout(94 downto 80);
                trunc_ln44_12_reg_491 <= layer28_out_dout(110 downto 96);
                trunc_ln44_14_reg_431 <= trunc_ln44_14_fu_117_p1;
                trunc_ln44_1_reg_436 <= layer28_out_dout(31 downto 16);
                trunc_ln44_2_reg_446 <= layer28_out_dout(47 downto 32);
                trunc_ln44_3_reg_456 <= layer28_out_dout(63 downto 48);
                trunc_ln44_4_reg_466 <= layer28_out_dout(79 downto 64);
                trunc_ln44_5_reg_476 <= layer28_out_dout(95 downto 80);
                trunc_ln44_6_reg_486 <= layer28_out_dout(111 downto 96);
                trunc_ln44_7_reg_496 <= layer28_out_dout(127 downto 112);
                trunc_ln44_8_reg_441 <= layer28_out_dout(30 downto 16);
                trunc_ln44_9_reg_451 <= layer28_out_dout(46 downto 32);
                trunc_ln44_reg_426 <= trunc_ln44_fu_113_p1;
                trunc_ln44_s_reg_461 <= layer28_out_dout(62 downto 48);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, layer28_out_empty_n, layer15_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((layer15_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((layer28_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, layer28_out_empty_n, layer15_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((layer15_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((layer28_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, layer28_out_empty_n, layer15_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((layer15_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((layer28_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, layer28_out_empty_n, layer15_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((layer15_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((layer28_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln41_fu_267_p2)
    begin
        if (((icmp_ln41_fu_267_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    i_5_fu_261_p2 <= std_logic_vector(unsigned(i_fu_88) + unsigned(ap_const_lv7_1));
    icmp_ln41_fu_267_p2 <= "1" when (i_fu_88 = ap_const_lv7_78) else "0";
    icmp_ln51_1_fu_290_p2 <= "1" when (signed(trunc_ln44_1_reg_436) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_2_fu_302_p2 <= "1" when (signed(trunc_ln44_2_reg_446) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_3_fu_314_p2 <= "1" when (signed(trunc_ln44_3_reg_456) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_4_fu_326_p2 <= "1" when (signed(trunc_ln44_4_reg_466) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_5_fu_338_p2 <= "1" when (signed(trunc_ln44_5_reg_476) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_6_fu_350_p2 <= "1" when (signed(trunc_ln44_6_reg_486) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_7_fu_362_p2 <= "1" when (signed(trunc_ln44_7_reg_496) > signed(ap_const_lv16_0)) else "0";
    icmp_ln51_fu_278_p2 <= "1" when (signed(trunc_ln44_reg_426) > signed(ap_const_lv16_0)) else "0";

    layer15_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, layer15_out_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer15_out_blk_n <= layer15_out_full_n;
        else 
            layer15_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer15_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_395_p9),128));

    layer15_out_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer15_out_write <= ap_const_logic_1;
        else 
            layer15_out_write <= ap_const_logic_0;
        end if; 
    end process;


    layer28_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer28_out_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer28_out_blk_n <= layer28_out_empty_n;
        else 
            layer28_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer28_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer28_out_read <= ap_const_logic_1;
        else 
            layer28_out_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_395_p9 <= (((((((select_ln51_7_reg_545 & zext_ln51_6_fu_392_p1) & zext_ln51_5_fu_389_p1) & zext_ln51_4_fu_386_p1) & zext_ln51_3_fu_383_p1) & zext_ln51_2_fu_380_p1) & zext_ln51_1_fu_377_p1) & zext_ln51_fu_374_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_1_fu_295_p3 <= 
        trunc_ln44_8_reg_441 when (icmp_ln51_1_fu_290_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_2_fu_307_p3 <= 
        trunc_ln44_9_reg_451 when (icmp_ln51_2_fu_302_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_3_fu_319_p3 <= 
        trunc_ln44_s_reg_461 when (icmp_ln51_3_fu_314_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_4_fu_331_p3 <= 
        trunc_ln44_10_reg_471 when (icmp_ln51_4_fu_326_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_5_fu_343_p3 <= 
        trunc_ln44_11_reg_481 when (icmp_ln51_5_fu_338_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_6_fu_355_p3 <= 
        trunc_ln44_12_reg_491 when (icmp_ln51_6_fu_350_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_7_fu_367_p3 <= 
        trunc_ln1_reg_501 when (icmp_ln51_7_fu_362_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln51_fu_283_p3 <= 
        trunc_ln44_14_reg_431 when (icmp_ln51_fu_278_p2(0) = '1') else 
        ap_const_lv15_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_14_fu_117_p1 <= layer28_out_dout(15 - 1 downto 0);
    trunc_ln44_fu_113_p1 <= layer28_out_dout(16 - 1 downto 0);
    zext_ln51_1_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_1_reg_515),16));
    zext_ln51_2_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_2_reg_520),16));
    zext_ln51_3_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_3_reg_525),16));
    zext_ln51_4_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_4_reg_530),16));
    zext_ln51_5_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_5_reg_535),16));
    zext_ln51_6_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_6_reg_540),16));
    zext_ln51_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_reg_510),16));
end behav;
